/**
 * Hand-authored application-level types that mirror database CHECK constraints
 * but are NOT part of the Supabase-generated schema.
 *
 * These used to live at the top of `database.types.ts`, but that file is now
 * auto-generated by `npm run gen:types` (CAR-142) and is overwritten wholesale
 * on every regeneration. Anything hand-written there would be lost, so the
 * durable app-level types live here instead. Per-column schema prose moved to
 * `supabase/database-reference/schema-notes.md`.
 */

// Guided first-run onboarding progress (CAR-50). Mirrors the CHECK constraint
// in 20260711003000_user_onboarding_state.sql; states are the flow's resume points.
export type OnboardingState =
  | "not_started"
  | "connect"
  | "syncing"
  | "pick_company"
  | "outreach"
  | "completed"
  | "skipped";

// Extension onboarding flow progress (CAR-68). Mirrors the CHECK constraint in
// 20260711140000_extension_onboarding.sql; states are the flow's resume points.
// 'done' and 'completed_no_apollo' are both terminal.
export type ExtensionOnboardingState =
  | "not_started"
  | "started"
  | "awaiting_connect"
  | "awaiting_first_contact"
  | "email_offer"
  | "apollo_intro"
  | "apollo_install"
  | "apollo_howto"
  | "awaiting_email_contact"
  | "done"
  | "completed_no_apollo";
