// AUTO-GENERATED by `npm run gen:types` (CAR-142). DO NOT EDIT BY HAND.
// Source of truth: supabase/migrations/*. Regenerate after any migration change.
// Per-table / per-column prose lives in supabase/database-reference/schema-notes.md.
// Hand-authored app-level types (OnboardingState, ...) live in src/lib/app-types.ts.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      action_item_contacts: {
        Row: {
          action_item_id: number
          contact_id: number
          id: number
        }
        Insert: {
          action_item_id: number
          contact_id: number
          id?: never
        }
        Update: {
          action_item_id?: number
          contact_id?: number
          id?: never
        }
        Relationships: [
          {
            foreignKeyName: "action_item_contacts_action_item_id_fkey"
            columns: ["action_item_id"]
            isOneToOne: false
            referencedRelation: "follow_up_action_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_item_contacts_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_audit_log: {
        Row: {
          action: string
          admin_id: string
          created_at: string
          detail: Json
          id: string
          outcome: string
          target_user_id: string | null
        }
        Insert: {
          action: string
          admin_id: string
          created_at?: string
          detail?: Json
          id?: string
          outcome?: string
          target_user_id?: string | null
        }
        Update: {
          action?: string
          admin_id?: string
          created_at?: string
          detail?: Json
          id?: string
          outcome?: string
          target_user_id?: string | null
        }
        Relationships: []
      }
      ai_follow_up_drafts: {
        Row: {
          article_source: string | null
          article_title: string | null
          article_url: string | null
          body_html: string
          contact_id: number
          created_at: string
          dismissed_at: string | null
          extracted_topic: string
          id: number
          recipient_email: string | null
          reply_thread_id: string | null
          reply_thread_subject: string | null
          send_as_reply: boolean
          sent_at: string | null
          source_meeting_id: number | null
          status: string
          subject: string
          topic_evidence: string
          updated_at: string
          user_id: string
        }
        Insert: {
          article_source?: string | null
          article_title?: string | null
          article_url?: string | null
          body_html: string
          contact_id: number
          created_at?: string
          dismissed_at?: string | null
          extracted_topic: string
          id?: never
          recipient_email?: string | null
          reply_thread_id?: string | null
          reply_thread_subject?: string | null
          send_as_reply?: boolean
          sent_at?: string | null
          source_meeting_id?: number | null
          status?: string
          subject: string
          topic_evidence: string
          updated_at?: string
          user_id: string
        }
        Update: {
          article_source?: string | null
          article_title?: string | null
          article_url?: string | null
          body_html?: string
          contact_id?: number
          created_at?: string
          dismissed_at?: string | null
          extracted_topic?: string
          id?: never
          recipient_email?: string | null
          reply_thread_id?: string | null
          reply_thread_subject?: string | null
          send_as_reply?: boolean
          sent_at?: string | null
          source_meeting_id?: number | null
          status?: string
          subject?: string
          topic_evidence?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_follow_up_drafts_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_follow_up_drafts_source_meeting_id_fkey"
            columns: ["source_meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_shared_usage: {
        Row: {
          call_count: number
          estimated_cost_usd: number
          period_start: string
          updated_at: string
          user_id: string
        }
        Insert: {
          call_count?: number
          estimated_cost_usd?: number
          period_start: string
          updated_at?: string
          user_id: string
        }
        Update: {
          call_count?: number
          estimated_cost_usd?: number
          period_start?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      analytics_events: {
        Row: {
          created_at: string
          event: string
          id: number
          properties: Json
          surface: string
          user_id: string
        }
        Insert: {
          created_at?: string
          event: string
          id?: never
          properties?: Json
          surface?: string
          user_id: string
        }
        Update: {
          created_at?: string
          event?: string
          id?: never
          properties?: Json
          surface?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "analytics_events_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      attachments: {
        Row: {
          bucket: string
          content_type: string | null
          created_at: string | null
          file_name: string
          file_size_bytes: number | null
          id: number
          is_public: boolean
          notes: string | null
          object_path: string
          user_id: string
        }
        Insert: {
          bucket: string
          content_type?: string | null
          created_at?: string | null
          file_name: string
          file_size_bytes?: number | null
          id?: number
          is_public?: boolean
          notes?: string | null
          object_path: string
          user_id: string
        }
        Update: {
          bucket?: string
          content_type?: string | null
          created_at?: string | null
          file_name?: string
          file_size_bytes?: number | null
          id?: number
          is_public?: boolean
          notes?: string | null
          object_path?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attachments_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      bundle_access_overrides: {
        Row: {
          allowed: boolean
          bundle_id: number
          updated_at: string
          updated_by: string | null
          user_id: string
        }
        Insert: {
          allowed: boolean
          bundle_id: number
          updated_at?: string
          updated_by?: string | null
          user_id: string
        }
        Update: {
          allowed?: boolean
          bundle_id?: number
          updated_at?: string
          updated_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bundle_access_overrides_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "data_bundles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_access_overrides_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_access_overrides_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      bundle_companies: {
        Row: {
          bundle_id: number
          company_id: number
          created_at: string
          id: number
          version_last_seen: number | null
        }
        Insert: {
          bundle_id: number
          company_id: number
          created_at?: string
          id?: number
          version_last_seen?: number | null
        }
        Update: {
          bundle_id?: number
          company_id?: number
          created_at?: string
          id?: number
          version_last_seen?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "bundle_companies_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "data_bundles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_companies_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      bundle_contact_state: {
        Row: {
          applied_fingerprint: string | null
          apply_started_at: string | null
          contact_id: number
          id: number
          updated_at: string
          user_id: string
          user_touched: boolean
        }
        Insert: {
          applied_fingerprint?: string | null
          apply_started_at?: string | null
          contact_id: number
          id?: number
          updated_at?: string
          user_id: string
          user_touched?: boolean
        }
        Update: {
          applied_fingerprint?: string | null
          apply_started_at?: string | null
          contact_id?: number
          id?: number
          updated_at?: string
          user_id?: string
          user_touched?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "bundle_contact_state_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_contact_state_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      bundle_prospects: {
        Row: {
          bundle_id: number
          created_at: string
          id: number
          linkedin_url: string
          payload: Json
          payload_hash: string
          payload_schema_version: number
          removed_in_version: number | null
          resolved: Json | null
          resolved_at: string | null
          updated_at: string
          version_added: number
          version_last_seen: number
          version_updated: number
        }
        Insert: {
          bundle_id: number
          created_at?: string
          id?: number
          linkedin_url: string
          payload: Json
          payload_hash: string
          payload_schema_version?: number
          removed_in_version?: number | null
          resolved?: Json | null
          resolved_at?: string | null
          updated_at?: string
          version_added: number
          version_last_seen: number
          version_updated: number
        }
        Update: {
          bundle_id?: number
          created_at?: string
          id?: number
          linkedin_url?: string
          payload?: Json
          payload_hash?: string
          payload_schema_version?: number
          removed_in_version?: number | null
          resolved?: Json | null
          resolved_at?: string | null
          updated_at?: string
          version_added?: number
          version_last_seen?: number
          version_updated?: number
        }
        Relationships: [
          {
            foreignKeyName: "bundle_prospects_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "data_bundles"
            referencedColumns: ["id"]
          },
        ]
      }
      bundle_subscription_contacts: {
        Row: {
          bundle_prospect_id: number | null
          contact_id: number
          created_by_bundle: boolean
          first_applied_version: number
          id: number
          last_applied_at: string
          last_applied_version: number
          linkedin_url: string
          subscription_id: number
        }
        Insert: {
          bundle_prospect_id?: number | null
          contact_id: number
          created_by_bundle: boolean
          first_applied_version: number
          id?: number
          last_applied_at?: string
          last_applied_version: number
          linkedin_url: string
          subscription_id: number
        }
        Update: {
          bundle_prospect_id?: number | null
          contact_id?: number
          created_by_bundle?: boolean
          first_applied_version?: number
          id?: number
          last_applied_at?: string
          last_applied_version?: number
          linkedin_url?: string
          subscription_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "bundle_subscription_contacts_bundle_prospect_id_fkey"
            columns: ["bundle_prospect_id"]
            isOneToOne: false
            referencedRelation: "bundle_prospects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_subscription_contacts_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_subscription_contacts_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: false
            referencedRelation: "bundle_subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      bundle_subscriptions: {
        Row: {
          bundle_id: number
          created_at: string
          id: number
          last_synced_at: string | null
          status: string
          sync_claimed_until: string | null
          sync_cursor: Json | null
          synced_version: number
          unsubscribe_keep_all: boolean | null
          updated_at: string
          user_id: string
        }
        Insert: {
          bundle_id: number
          created_at?: string
          id?: number
          last_synced_at?: string | null
          status?: string
          sync_claimed_until?: string | null
          sync_cursor?: Json | null
          synced_version?: number
          unsubscribe_keep_all?: boolean | null
          updated_at?: string
          user_id: string
        }
        Update: {
          bundle_id?: number
          created_at?: string
          id?: number
          last_synced_at?: string | null
          status?: string
          sync_claimed_until?: string | null
          sync_cursor?: Json | null
          synced_version?: number
          unsubscribe_keep_all?: boolean | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bundle_subscriptions_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "data_bundles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      calendar_event_contacts: {
        Row: {
          calendar_event_id: number
          contact_id: number
        }
        Insert: {
          calendar_event_id: number
          contact_id: number
        }
        Update: {
          calendar_event_id?: number
          contact_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "calendar_event_contacts_calendar_event_id_fkey"
            columns: ["calendar_event_id"]
            isOneToOne: false
            referencedRelation: "calendar_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_event_contacts_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      calendar_events: {
        Row: {
          all_day: boolean | null
          attendees: Json | null
          calendar_id: string
          contact_id: number | null
          created_at: string | null
          description: string | null
          end_at: string
          google_event_id: string
          id: number
          is_private: boolean | null
          location: string | null
          meet_link: string | null
          meeting_id: number | null
          recurring_event_id: string | null
          source_gmail_message_id: string | null
          source_gmail_thread_id: string | null
          start_at: string
          status: string | null
          synced_at: string | null
          title: string | null
          user_id: string
          zoom_link: string | null
        }
        Insert: {
          all_day?: boolean | null
          attendees?: Json | null
          calendar_id?: string
          contact_id?: number | null
          created_at?: string | null
          description?: string | null
          end_at: string
          google_event_id: string
          id?: number
          is_private?: boolean | null
          location?: string | null
          meet_link?: string | null
          meeting_id?: number | null
          recurring_event_id?: string | null
          source_gmail_message_id?: string | null
          source_gmail_thread_id?: string | null
          start_at: string
          status?: string | null
          synced_at?: string | null
          title?: string | null
          user_id: string
          zoom_link?: string | null
        }
        Update: {
          all_day?: boolean | null
          attendees?: Json | null
          calendar_id?: string
          contact_id?: number | null
          created_at?: string | null
          description?: string | null
          end_at?: string
          google_event_id?: string
          id?: number
          is_private?: boolean | null
          location?: string | null
          meet_link?: string | null
          meeting_id?: number | null
          recurring_event_id?: string | null
          source_gmail_message_id?: string | null
          source_gmail_thread_id?: string | null
          start_at?: string
          status?: string | null
          synced_at?: string | null
          title?: string | null
          user_id?: string
          zoom_link?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "calendar_events_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_events_meeting_id_fkey"
            columns: ["meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          id: number
          linkedin_company_id: string | null
          linkedin_url: string | null
          logo_url: string | null
          name: string
          name_normalized: string | null
          universal_name: string | null
        }
        Insert: {
          id?: number
          linkedin_company_id?: string | null
          linkedin_url?: string | null
          logo_url?: string | null
          name: string
          name_normalized?: string | null
          universal_name?: string | null
        }
        Update: {
          id?: number
          linkedin_company_id?: string | null
          linkedin_url?: string | null
          logo_url?: string | null
          name?: string
          name_normalized?: string | null
          universal_name?: string | null
        }
        Relationships: []
      }
      company_locations: {
        Row: {
          company_id: number
          created_at: string
          id: number
          location_id: number
          source: string
        }
        Insert: {
          company_id: number
          created_at?: string
          id?: number
          location_id: number
          source?: string
        }
        Update: {
          company_id?: number
          created_at?: string
          id?: number
          location_id?: number
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "company_locations_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "company_locations_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_attachments: {
        Row: {
          attachment_id: number
          contact_id: number
        }
        Insert: {
          attachment_id: number
          contact_id: number
        }
        Update: {
          attachment_id?: number
          contact_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "contact_attachments_attachment_fk"
            columns: ["attachment_id"]
            isOneToOne: false
            referencedRelation: "attachments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_attachments_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_change_events: {
        Row: {
          actioned_at: string | null
          contact_id: number
          dedupe_key: string
          detected_at: string
          evidence: string | null
          headline: string
          id: number
          new_value: Json | null
          old_value: Json | null
          snoozed_until: string | null
          status: string
          suggested_description: string | null
          suggested_title: string | null
          tier: number
          type: string
          user_id: string
        }
        Insert: {
          actioned_at?: string | null
          contact_id: number
          dedupe_key: string
          detected_at?: string
          evidence?: string | null
          headline: string
          id?: number
          new_value?: Json | null
          old_value?: Json | null
          snoozed_until?: string | null
          status?: string
          suggested_description?: string | null
          suggested_title?: string | null
          tier?: number
          type: string
          user_id: string
        }
        Update: {
          actioned_at?: string | null
          contact_id?: number
          dedupe_key?: string
          detected_at?: string
          evidence?: string | null
          headline?: string
          id?: number
          new_value?: Json | null
          old_value?: Json | null
          snoozed_until?: string | null
          status?: string
          suggested_description?: string | null
          suggested_title?: string | null
          tier?: number
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_change_events_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_change_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_companies: {
        Row: {
          company_id: number
          contact_id: number
          employment_type: string | null
          end_date: string | null
          end_month: string | null
          id: number
          is_current: boolean
          location: string | null
          location_id: number | null
          location_raw: string | null
          location_source: string | null
          scraped_at: string | null
          source: string
          start_date: string | null
          start_month: string | null
          title: string | null
          workplace_type: string | null
        }
        Insert: {
          company_id: number
          contact_id: number
          employment_type?: string | null
          end_date?: string | null
          end_month?: string | null
          id?: number
          is_current?: boolean
          location?: string | null
          location_id?: number | null
          location_raw?: string | null
          location_source?: string | null
          scraped_at?: string | null
          source?: string
          start_date?: string | null
          start_month?: string | null
          title?: string | null
          workplace_type?: string | null
        }
        Update: {
          company_id?: number
          contact_id?: number
          employment_type?: string | null
          end_date?: string | null
          end_month?: string | null
          id?: number
          is_current?: boolean
          location?: string | null
          location_id?: number | null
          location_raw?: string | null
          location_source?: string | null
          scraped_at?: string | null
          source?: string
          start_date?: string | null
          start_month?: string | null
          title?: string | null
          workplace_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contact_companies_company_fk"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_companies_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_companies_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_emails: {
        Row: {
          bounced_at: string | null
          contact_id: number
          email: string | null
          id: number
          is_primary: boolean
          source: string
        }
        Insert: {
          bounced_at?: string | null
          contact_id: number
          email?: string | null
          id?: number
          is_primary?: boolean
          source?: string
        }
        Update: {
          bounced_at?: string | null
          contact_id?: number
          email?: string | null
          id?: number
          is_primary?: boolean
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_emails_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_phones: {
        Row: {
          contact_id: number
          id: number
          is_primary: boolean
          phone: string
          type: string
        }
        Insert: {
          contact_id: number
          id?: number
          is_primary?: boolean
          phone: string
          type?: string
        }
        Update: {
          contact_id?: number
          id?: number
          is_primary?: boolean
          phone?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_phones_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_schools: {
        Row: {
          contact_id: number
          degree: string | null
          end_year: number | null
          field_of_study: string | null
          id: number
          school_id: number
          start_year: number | null
        }
        Insert: {
          contact_id: number
          degree?: string | null
          end_year?: number | null
          field_of_study?: string | null
          id?: number
          school_id: number
          start_year?: number | null
        }
        Update: {
          contact_id?: number
          degree?: string | null
          end_year?: number | null
          field_of_study?: string | null
          id?: number
          school_id?: number
          start_year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "contact_schools_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_schools_school_fk"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_scrape_snapshots: {
        Row: {
          contact_id: number
          id: number
          scrape_run_id: number | null
          scraped_at: string
          snapshot: Json
          user_id: string
        }
        Insert: {
          contact_id: number
          id?: number
          scrape_run_id?: number | null
          scraped_at?: string
          snapshot: Json
          user_id: string
        }
        Update: {
          contact_id?: number
          id?: number
          scrape_run_id?: number | null
          scraped_at?: string
          snapshot?: Json
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_scrape_snapshots_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_scrape_snapshots_scrape_run_id_fkey"
            columns: ["scrape_run_id"]
            isOneToOne: false
            referencedRelation: "scrape_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_scrape_snapshots_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_tags: {
        Row: {
          contact_id: number
          tag_id: number
        }
        Insert: {
          contact_id: number
          tag_id: number
        }
        Update: {
          contact_id?: number
          tag_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "contact_tags_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_tags_tag_fk"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          contact_status: string | null
          created_at: string
          email_synced_through: string | null
          expected_graduation: string | null
          first_outreach_skipped: boolean
          follow_up_frequency_days: number | null
          headline: string | null
          id: number
          import_meta: Json | null
          import_source: string | null
          industry: string | null
          intro_goal: string | null
          last_scraped_at: string | null
          linkedin_url: string | null
          location_id: number | null
          met_through: string | null
          name: string
          network_scope: string | null
          network_status: string
          notes: string | null
          persona: string | null
          photo_url: string | null
          preferred_contact_method: string | null
          preferred_contact_value: string | null
          public_identifier: string | null
          reach_out_snoozed_until: string | null
          review_note: string | null
          scrape_failed_at: string | null
          scrape_failure_count: number
          stage_override: string | null
          status_derived_at: string | null
          suggestion_cooldown_until: string | null
          user_id: string
          verified_school: string | null
        }
        Insert: {
          contact_status?: string | null
          created_at?: string
          email_synced_through?: string | null
          expected_graduation?: string | null
          first_outreach_skipped?: boolean
          follow_up_frequency_days?: number | null
          headline?: string | null
          id?: number
          import_meta?: Json | null
          import_source?: string | null
          industry?: string | null
          intro_goal?: string | null
          last_scraped_at?: string | null
          linkedin_url?: string | null
          location_id?: number | null
          met_through?: string | null
          name: string
          network_scope?: string | null
          network_status?: string
          notes?: string | null
          persona?: string | null
          photo_url?: string | null
          preferred_contact_method?: string | null
          preferred_contact_value?: string | null
          public_identifier?: string | null
          reach_out_snoozed_until?: string | null
          review_note?: string | null
          scrape_failed_at?: string | null
          scrape_failure_count?: number
          stage_override?: string | null
          status_derived_at?: string | null
          suggestion_cooldown_until?: string | null
          user_id: string
          verified_school?: string | null
        }
        Update: {
          contact_status?: string | null
          created_at?: string
          email_synced_through?: string | null
          expected_graduation?: string | null
          first_outreach_skipped?: boolean
          follow_up_frequency_days?: number | null
          headline?: string | null
          id?: number
          import_meta?: Json | null
          import_source?: string | null
          industry?: string | null
          intro_goal?: string | null
          last_scraped_at?: string | null
          linkedin_url?: string | null
          location_id?: number | null
          met_through?: string | null
          name?: string
          network_scope?: string | null
          network_status?: string
          notes?: string | null
          persona?: string | null
          photo_url?: string | null
          preferred_contact_method?: string | null
          preferred_contact_value?: string | null
          public_identifier?: string | null
          reach_out_snoozed_until?: string | null
          review_note?: string | null
          scrape_failed_at?: string | null
          scrape_failure_count?: number
          stage_override?: string | null
          status_derived_at?: string | null
          suggestion_cooldown_until?: string | null
          user_id?: string
          verified_school?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contacts_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      data_bundles: {
        Row: {
          company_count: number
          created_at: string
          default_visible: boolean
          description: string | null
          id: number
          name: string
          prospect_count: number
          published_at: string | null
          resolved_version: number
          slug: string
          staging_claimed_at: string | null
          staging_version: number | null
          status: string
          updated_at: string
          version: number
        }
        Insert: {
          company_count?: number
          created_at?: string
          default_visible?: boolean
          description?: string | null
          id?: number
          name: string
          prospect_count?: number
          published_at?: string | null
          resolved_version?: number
          slug: string
          staging_claimed_at?: string | null
          staging_version?: number | null
          status?: string
          updated_at?: string
          version?: number
        }
        Update: {
          company_count?: number
          created_at?: string
          default_visible?: boolean
          description?: string | null
          id?: number
          name?: string
          prospect_count?: number
          published_at?: string | null
          resolved_version?: number
          slug?: string
          staging_claimed_at?: string | null
          staging_version?: number | null
          status?: string
          updated_at?: string
          version?: number
        }
        Relationships: []
      }
      discovery_candidates: {
        Row: {
          added_contact_id: number | null
          company_id: number
          first_seen_at: string
          headline: string | null
          id: number
          last_seen_at: string
          linkedin_url: string
          location: string | null
          name: string
          photo_url: string | null
          position: string | null
          public_identifier: string | null
          raw: Json
          status: string
          user_id: string
        }
        Insert: {
          added_contact_id?: number | null
          company_id: number
          first_seen_at?: string
          headline?: string | null
          id?: number
          last_seen_at?: string
          linkedin_url: string
          location?: string | null
          name: string
          photo_url?: string | null
          position?: string | null
          public_identifier?: string | null
          raw: Json
          status?: string
          user_id: string
        }
        Update: {
          added_contact_id?: number | null
          company_id?: number
          first_seen_at?: string
          headline?: string | null
          id?: number
          last_seen_at?: string
          linkedin_url?: string
          location?: string | null
          name?: string
          photo_url?: string | null
          position?: string | null
          public_identifier?: string | null
          raw?: Json
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "discovery_candidates_added_contact_id_fkey"
            columns: ["added_contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "discovery_candidates_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "discovery_candidates_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      email_drafts: {
        Row: {
          bcc: string | null
          body_html: string | null
          cc: string | null
          contact_name: string | null
          created_at: string
          id: number
          in_reply_to: string | null
          recipient_email: string | null
          references_header: string | null
          subject: string | null
          thread_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          bcc?: string | null
          body_html?: string | null
          cc?: string | null
          contact_name?: string | null
          created_at?: string
          id?: never
          in_reply_to?: string | null
          recipient_email?: string | null
          references_header?: string | null
          subject?: string | null
          thread_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          bcc?: string | null
          body_html?: string | null
          cc?: string | null
          contact_name?: string | null
          created_at?: string
          id?: never
          in_reply_to?: string | null
          recipient_email?: string | null
          references_header?: string | null
          subject?: string | null
          thread_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      email_follow_up_messages: {
        Row: {
          body_html: string
          claimed_at: string | null
          created_at: string | null
          expires_at: string | null
          follow_up_id: number
          id: number
          last_reminder_at: string | null
          parked_at: string | null
          reminder_count: number
          scheduled_send_at: string
          seen_during_window: boolean
          send_after_days: number
          sent_at: string | null
          sequence_number: number
          status: string
          subject: string
        }
        Insert: {
          body_html: string
          claimed_at?: string | null
          created_at?: string | null
          expires_at?: string | null
          follow_up_id: number
          id?: number
          last_reminder_at?: string | null
          parked_at?: string | null
          reminder_count?: number
          scheduled_send_at: string
          seen_during_window?: boolean
          send_after_days: number
          sent_at?: string | null
          sequence_number: number
          status?: string
          subject: string
        }
        Update: {
          body_html?: string
          claimed_at?: string | null
          created_at?: string | null
          expires_at?: string | null
          follow_up_id?: number
          id?: number
          last_reminder_at?: string | null
          parked_at?: string | null
          reminder_count?: number
          scheduled_send_at?: string
          seen_during_window?: boolean
          send_after_days?: number
          sent_at?: string | null
          sequence_number?: number
          status?: string
          subject?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_follow_up_messages_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "email_follow_ups"
            referencedColumns: ["id"]
          },
        ]
      }
      email_follow_ups: {
        Row: {
          contact_id: number | null
          contact_name: string | null
          created_at: string | null
          id: number
          original_gmail_message_id: string | null
          original_sent_at: string
          original_subject: string | null
          recipient_email: string
          scheduled_email_id: number | null
          status: string
          thread_id: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          contact_id?: number | null
          contact_name?: string | null
          created_at?: string | null
          id?: number
          original_gmail_message_id?: string | null
          original_sent_at: string
          original_subject?: string | null
          recipient_email: string
          scheduled_email_id?: number | null
          status?: string
          thread_id?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          contact_id?: number | null
          contact_name?: string | null
          created_at?: string | null
          id?: number
          original_gmail_message_id?: string | null
          original_sent_at?: string
          original_subject?: string | null
          recipient_email?: string
          scheduled_email_id?: number | null
          status?: string
          thread_id?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_follow_ups_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "email_follow_ups_scheduled_email_id_fkey"
            columns: ["scheduled_email_id"]
            isOneToOne: false
            referencedRelation: "scheduled_emails"
            referencedColumns: ["id"]
          },
        ]
      }
      email_messages: {
        Row: {
          ai_assisted: boolean
          body_html: string | null
          created_at: string | null
          date: string | null
          direction: string | null
          from_address: string | null
          gmail_message_id: string
          id: number
          is_hidden: boolean
          is_read: boolean | null
          is_simulated: boolean | null
          is_trashed: boolean
          label_ids: string[] | null
          matched_contact_id: number | null
          snippet: string | null
          subject: string | null
          thread_id: string | null
          to_addresses: string[] | null
          user_id: string
        }
        Insert: {
          ai_assisted?: boolean
          body_html?: string | null
          created_at?: string | null
          date?: string | null
          direction?: string | null
          from_address?: string | null
          gmail_message_id: string
          id?: number
          is_hidden?: boolean
          is_read?: boolean | null
          is_simulated?: boolean | null
          is_trashed?: boolean
          label_ids?: string[] | null
          matched_contact_id?: number | null
          snippet?: string | null
          subject?: string | null
          thread_id?: string | null
          to_addresses?: string[] | null
          user_id: string
        }
        Update: {
          ai_assisted?: boolean
          body_html?: string | null
          created_at?: string | null
          date?: string | null
          direction?: string | null
          from_address?: string | null
          gmail_message_id?: string
          id?: number
          is_hidden?: boolean
          is_read?: boolean | null
          is_simulated?: boolean | null
          is_trashed?: boolean
          label_ids?: string[] | null
          matched_contact_id?: number | null
          snippet?: string | null
          subject?: string | null
          thread_id?: string | null
          to_addresses?: string[] | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_messages_matched_contact_id_fkey"
            columns: ["matched_contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      email_templates: {
        Row: {
          created_at: string
          id: number
          is_default: boolean
          name: string
          prompt: string
          sort_order: number
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          is_default?: boolean
          name: string
          prompt: string
          sort_order?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: never
          is_default?: boolean
          name?: string
          prompt?: string
          sort_order?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      follow_up_action_items: {
        Row: {
          assigned_speaker: string | null
          completed_at: string | null
          contact_id: number | null
          created_at: string | null
          description: string | null
          direction: string | null
          due_at: string | null
          id: number
          is_completed: boolean
          meeting_id: number | null
          priority: string | null
          related_action_item_id: number | null
          snoozed_until: string | null
          source: string
          suggestion_evidence: string | null
          suggestion_headline: string | null
          suggestion_reason_type: string | null
          title: string
          user_id: string
        }
        Insert: {
          assigned_speaker?: string | null
          completed_at?: string | null
          contact_id?: number | null
          created_at?: string | null
          description?: string | null
          direction?: string | null
          due_at?: string | null
          id?: number
          is_completed?: boolean
          meeting_id?: number | null
          priority?: string | null
          related_action_item_id?: number | null
          snoozed_until?: string | null
          source?: string
          suggestion_evidence?: string | null
          suggestion_headline?: string | null
          suggestion_reason_type?: string | null
          title: string
          user_id: string
        }
        Update: {
          assigned_speaker?: string | null
          completed_at?: string | null
          contact_id?: number | null
          created_at?: string | null
          description?: string | null
          direction?: string | null
          due_at?: string | null
          id?: number
          is_completed?: boolean
          meeting_id?: number | null
          priority?: string | null
          related_action_item_id?: number | null
          snoozed_until?: string | null
          source?: string
          suggestion_evidence?: string | null
          suggestion_headline?: string | null
          suggestion_reason_type?: string | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_up_action_items_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_up_action_items_meeting_fk"
            columns: ["meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_up_action_items_related_action_item_id_fkey"
            columns: ["related_action_item_id"]
            isOneToOne: false
            referencedRelation: "follow_up_action_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_up_action_items_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      gmail_connections: {
        Row: {
          access_token: string
          automatic_features_enabled: boolean
          availability_priority: Json | null
          availability_standard: Json | null
          busy_calendar_ids: string[] | null
          calendar_last_synced_at: string | null
          calendar_list: Json | null
          calendar_scopes_granted: boolean | null
          calendar_sync_token: string | null
          calendar_timezone: string | null
          created_at: string | null
          gmail_address: string
          id: number
          last_gmail_sync_at: string | null
          modify_scope_granted: boolean
          premium_enabled: boolean
          refresh_token: string
          send_as_aliases: Json | null
          send_scope_granted: boolean
          token_expires_at: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          access_token: string
          automatic_features_enabled?: boolean
          availability_priority?: Json | null
          availability_standard?: Json | null
          busy_calendar_ids?: string[] | null
          calendar_last_synced_at?: string | null
          calendar_list?: Json | null
          calendar_scopes_granted?: boolean | null
          calendar_sync_token?: string | null
          calendar_timezone?: string | null
          created_at?: string | null
          gmail_address: string
          id?: number
          last_gmail_sync_at?: string | null
          modify_scope_granted?: boolean
          premium_enabled?: boolean
          refresh_token: string
          send_as_aliases?: Json | null
          send_scope_granted?: boolean
          token_expires_at: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          access_token?: string
          automatic_features_enabled?: boolean
          availability_priority?: Json | null
          availability_standard?: Json | null
          busy_calendar_ids?: string[] | null
          calendar_last_synced_at?: string | null
          calendar_list?: Json | null
          calendar_scopes_granted?: boolean | null
          calendar_sync_token?: string | null
          calendar_timezone?: string | null
          created_at?: string | null
          gmail_address?: string
          id?: number
          last_gmail_sync_at?: string | null
          modify_scope_granted?: boolean
          premium_enabled?: boolean
          refresh_token?: string
          send_as_aliases?: Json | null
          send_scope_granted?: boolean
          token_expires_at?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      interaction_attachments: {
        Row: {
          attachment_id: number
          interaction_id: number
        }
        Insert: {
          attachment_id: number
          interaction_id: number
        }
        Update: {
          attachment_id?: number
          interaction_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "interaction_attachments_attachment_fk"
            columns: ["attachment_id"]
            isOneToOne: false
            referencedRelation: "attachments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interaction_attachments_interaction_fk"
            columns: ["interaction_id"]
            isOneToOne: false
            referencedRelation: "interactions"
            referencedColumns: ["id"]
          },
        ]
      }
      interactions: {
        Row: {
          contact_id: number
          id: number
          interaction_date: string
          interaction_type: string
          summary: string | null
        }
        Insert: {
          contact_id: number
          id?: number
          interaction_date: string
          interaction_type: string
          summary?: string | null
        }
        Update: {
          contact_id?: number
          id?: number
          interaction_date?: string
          interaction_type?: string
          summary?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "interactions_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      internal_analytics_emails: {
        Row: {
          created_at: string
          email: string
          note: string | null
        }
        Insert: {
          created_at?: string
          email: string
          note?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          note?: string | null
        }
        Relationships: []
      }
      locations: {
        Row: {
          city: string | null
          country: string
          id: number
          state: string | null
        }
        Insert: {
          city?: string | null
          country?: string
          id?: number
          state?: string | null
        }
        Update: {
          city?: string | null
          country?: string
          id?: number
          state?: string | null
        }
        Relationships: []
      }
      meeting_attachments: {
        Row: {
          attachment_id: number
          meeting_id: number
        }
        Insert: {
          attachment_id: number
          meeting_id: number
        }
        Update: {
          attachment_id?: number
          meeting_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "meeting_attachments_attachment_fk"
            columns: ["attachment_id"]
            isOneToOne: false
            referencedRelation: "attachments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meeting_attachments_meeting_fk"
            columns: ["meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
        ]
      }
      meeting_contacts: {
        Row: {
          contact_id: number
          meeting_id: number
        }
        Insert: {
          contact_id: number
          meeting_id: number
        }
        Update: {
          contact_id?: number
          meeting_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "meeting_contacts_contact_fk"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meeting_contacts_meeting_fk"
            columns: ["meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
        ]
      }
      meetings: {
        Row: {
          calendar_description: string | null
          calendar_event_id: string | null
          id: number
          meet_link: string | null
          meeting_date: string
          meeting_type: string | null
          notes: string | null
          private_notes: string | null
          title: string | null
          transcript: string | null
          transcript_attachment_id: number | null
          transcript_parsed: boolean | null
          transcript_source: string | null
          user_id: string
          zoom_link: string | null
        }
        Insert: {
          calendar_description?: string | null
          calendar_event_id?: string | null
          id?: number
          meet_link?: string | null
          meeting_date: string
          meeting_type?: string | null
          notes?: string | null
          private_notes?: string | null
          title?: string | null
          transcript?: string | null
          transcript_attachment_id?: number | null
          transcript_parsed?: boolean | null
          transcript_source?: string | null
          user_id: string
          zoom_link?: string | null
        }
        Update: {
          calendar_description?: string | null
          calendar_event_id?: string | null
          id?: number
          meet_link?: string | null
          meeting_date?: string
          meeting_type?: string | null
          notes?: string | null
          private_notes?: string | null
          title?: string | null
          transcript?: string | null
          transcript_attachment_id?: number | null
          transcript_parsed?: boolean | null
          transcript_source?: string | null
          user_id?: string
          zoom_link?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "meetings_transcript_attachment_id_fkey"
            columns: ["transcript_attachment_id"]
            isOneToOne: false
            referencedRelation: "attachments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meetings_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_applications: {
        Row: {
          cover_letter_name: string | null
          cover_letter_path: string | null
          cover_letter_size_bytes: number | null
          created_at: string
          cycle_id: number
          date_applied: string | null
          id: string
          job_title: string
          location: string
          position: number
          resume_name: string | null
          resume_path: string | null
          resume_size_bytes: number | null
        }
        Insert: {
          cover_letter_name?: string | null
          cover_letter_path?: string | null
          cover_letter_size_bytes?: number | null
          created_at?: string
          cycle_id: number
          date_applied?: string | null
          id: string
          job_title?: string
          location?: string
          position?: number
          resume_name?: string | null
          resume_path?: string | null
          resume_size_bytes?: number | null
        }
        Update: {
          cover_letter_name?: string | null
          cover_letter_path?: string | null
          cover_letter_size_bytes?: number | null
          created_at?: string
          cycle_id?: number
          date_applied?: string | null
          id?: string
          job_title?: string
          location?: string
          position?: number
          resume_name?: string | null
          resume_path?: string | null
          resume_size_bytes?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "pipeline_applications_cycle_id_fkey"
            columns: ["cycle_id"]
            isOneToOne: false
            referencedRelation: "pipeline_cycles"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_cycles: {
        Row: {
          created_at: string
          cycle_number: number
          declined_next_cycle: boolean
          id: number
          selected_stage: string
          target_company_id: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          cycle_number: number
          declined_next_cycle?: boolean
          id?: number
          selected_stage?: string
          target_company_id: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          cycle_number?: number
          declined_next_cycle?: boolean
          id?: number
          selected_stage?: string
          target_company_id?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "pipeline_cycles_target_company_id_fkey"
            columns: ["target_company_id"]
            isOneToOne: false
            referencedRelation: "target_companies"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_interview_rounds: {
        Row: {
          created_at: string
          cycle_id: number
          id: string
          interview_date: string | null
          interviewer: string
          position: number
          questions: string
        }
        Insert: {
          created_at?: string
          cycle_id: number
          id: string
          interview_date?: string | null
          interviewer?: string
          position?: number
          questions?: string
        }
        Update: {
          created_at?: string
          cycle_id?: number
          id?: string
          interview_date?: string | null
          interviewer?: string
          position?: number
          questions?: string
        }
        Relationships: [
          {
            foreignKeyName: "pipeline_interview_rounds_cycle_id_fkey"
            columns: ["cycle_id"]
            isOneToOne: false
            referencedRelation: "pipeline_cycles"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_notes: {
        Row: {
          body: string
          created_at: string
          cycle_id: number
          id: string
          position: number
        }
        Insert: {
          body?: string
          created_at?: string
          cycle_id: number
          id: string
          position?: number
        }
        Update: {
          body?: string
          created_at?: string
          cycle_id?: number
          id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "pipeline_notes_cycle_id_fkey"
            columns: ["cycle_id"]
            isOneToOne: false
            referencedRelation: "pipeline_cycles"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_programs: {
        Row: {
          apps_open: string
          created_at: string
          cycle_id: number
          id: string
          job_potential: string
          name: string
          position: number
        }
        Insert: {
          apps_open?: string
          created_at?: string
          cycle_id: number
          id: string
          job_potential?: string
          name?: string
          position?: number
        }
        Update: {
          apps_open?: string
          created_at?: string
          cycle_id?: number
          id?: string
          job_potential?: string
          name?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "pipeline_programs_cycle_id_fkey"
            columns: ["cycle_id"]
            isOneToOne: false
            referencedRelation: "pipeline_cycles"
            referencedColumns: ["id"]
          },
        ]
      }
      referrals: {
        Row: {
          id: number
          notes: string | null
          referral_meeting_id: number | null
          referred_by_contact_id: number
          referred_contact_id: number
          user_id: string
        }
        Insert: {
          id?: number
          notes?: string | null
          referral_meeting_id?: number | null
          referred_by_contact_id: number
          referred_contact_id: number
          user_id: string
        }
        Update: {
          id?: number
          notes?: string | null
          referral_meeting_id?: number | null
          referred_by_contact_id?: number
          referred_contact_id?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "referrals_contact_fk"
            columns: ["referred_contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referrals_meeting_fk"
            columns: ["referral_meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referrals_referrer_fk"
            columns: ["referred_by_contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referrals_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      scheduled_emails: {
        Row: {
          bcc: string | null
          body_html: string
          cc: string | null
          claimed_at: string | null
          contact_name: string | null
          created_at: string | null
          gmail_message_id: string | null
          id: number
          in_reply_to: string | null
          matched_contact_id: number | null
          recipient_email: string
          references_header: string | null
          scheduled_send_at: string
          sent_at: string | null
          sent_thread_id: string | null
          status: string
          subject: string
          thread_id: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          bcc?: string | null
          body_html: string
          cc?: string | null
          claimed_at?: string | null
          contact_name?: string | null
          created_at?: string | null
          gmail_message_id?: string | null
          id?: number
          in_reply_to?: string | null
          matched_contact_id?: number | null
          recipient_email: string
          references_header?: string | null
          scheduled_send_at: string
          sent_at?: string | null
          sent_thread_id?: string | null
          status?: string
          subject: string
          thread_id?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          bcc?: string | null
          body_html?: string
          cc?: string | null
          claimed_at?: string | null
          contact_name?: string | null
          created_at?: string | null
          gmail_message_id?: string | null
          id?: number
          in_reply_to?: string | null
          matched_contact_id?: number | null
          recipient_email?: string
          references_header?: string | null
          scheduled_send_at?: string
          sent_at?: string | null
          sent_thread_id?: string | null
          status?: string
          subject?: string
          thread_id?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scheduled_emails_matched_contact_id_fkey"
            columns: ["matched_contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      schools: {
        Row: {
          id: number
          name: string
        }
        Insert: {
          id?: number
          name: string
        }
        Update: {
          id?: number
          name?: string
        }
        Relationships: []
      }
      scrape_runs: {
        Row: {
          actor: string
          apify_run_id: string | null
          company_id: number | null
          contact_ids: number[]
          cost_usd: number
          created_at: string
          error: string | null
          finished_at: string | null
          id: number
          ingest_claimed_at: string | null
          mode: string
          single_contact_id: number | null
          status: string
          trigger: string
          user_id: string
        }
        Insert: {
          actor: string
          apify_run_id?: string | null
          company_id?: number | null
          contact_ids?: number[]
          cost_usd?: number
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: number
          ingest_claimed_at?: string | null
          mode: string
          single_contact_id?: number | null
          status?: string
          trigger: string
          user_id: string
        }
        Update: {
          actor?: string
          apify_run_id?: string | null
          company_id?: number | null
          contact_ids?: number[]
          cost_usd?: number
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: number
          ingest_claimed_at?: string | null
          mode?: string
          single_contact_id?: number | null
          status?: string
          trigger?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scrape_runs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scrape_runs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      suppressed_imports: {
        Row: {
          created_at: string
          id: number
          linkedin_url: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: number
          linkedin_url: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: number
          linkedin_url?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "suppressed_imports_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      tags: {
        Row: {
          id: number
          name: string
          user_id: string
        }
        Insert: {
          id?: number
          name: string
          user_id: string
        }
        Update: {
          id?: number
          name?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tags_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      target_companies: {
        Row: {
          active_cycle: number
          app_window_text: string | null
          company_id: number
          created_at: string
          id: number
          is_targeted: boolean
          last_discovery_at: string | null
          location_id: number | null
          next_app_date: string | null
          priority_score: number | null
          program_name: string | null
          status: string
          tier: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          active_cycle?: number
          app_window_text?: string | null
          company_id: number
          created_at?: string
          id?: number
          is_targeted?: boolean
          last_discovery_at?: string | null
          location_id?: number | null
          next_app_date?: string | null
          priority_score?: number | null
          program_name?: string | null
          status?: string
          tier?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          active_cycle?: number
          app_window_text?: string | null
          company_id?: number
          created_at?: string
          id?: number
          is_targeted?: boolean
          last_discovery_at?: string | null
          location_id?: number | null
          next_app_date?: string | null
          priority_score?: number | null
          program_name?: string | null
          status?: string
          tier?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "target_companies_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "target_companies_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "target_companies_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      target_company_notes: {
        Row: {
          created_at: string
          id: number
          location_id: number | null
          note: string
          target_company_id: number
        }
        Insert: {
          created_at?: string
          id?: number
          location_id?: number | null
          note: string
          target_company_id: number
        }
        Update: {
          created_at?: string
          id?: number
          location_id?: number | null
          note?: string
          target_company_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "target_company_notes_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "target_company_notes_target_company_id_fkey"
            columns: ["target_company_id"]
            isOneToOne: false
            referencedRelation: "target_companies"
            referencedColumns: ["id"]
          },
        ]
      }
      transcript_segments: {
        Row: {
          contact_id: number | null
          content: string
          created_at: string | null
          ended_at: number | null
          id: number
          meeting_id: number
          ordinal: number
          speaker_label: string
          started_at: number | null
        }
        Insert: {
          contact_id?: number | null
          content: string
          created_at?: string | null
          ended_at?: number | null
          id?: never
          meeting_id: number
          ordinal: number
          speaker_label: string
          started_at?: number | null
        }
        Update: {
          contact_id?: number | null
          content?: string
          created_at?: string | null
          ended_at?: number | null
          id?: never
          meeting_id?: number
          ordinal?: number
          speaker_label?: string
          started_at?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "transcript_segments_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transcript_segments_meeting_id_fkey"
            columns: ["meeting_id"]
            isOneToOne: false
            referencedRelation: "meetings"
            referencedColumns: ["id"]
          },
        ]
      }
      user_ai_access: {
        Row: {
          access_requested_at: string | null
          created_at: string
          expires_at: string | null
          granted_at: string | null
          granted_by: string | null
          shared_access: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          access_requested_at?: string | null
          created_at?: string
          expires_at?: string | null
          granted_at?: string | null
          granted_by?: string | null
          shared_access?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          access_requested_at?: string | null
          created_at?: string
          expires_at?: string | null
          granted_at?: string | null
          granted_by?: string | null
          shared_access?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_api_keys: {
        Row: {
          created_at: string
          encrypted_key: string
          key_last4: string
          last_used_at: string | null
          last_validated_at: string | null
          provider: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          encrypted_key: string
          key_last4: string
          last_used_at?: string | null
          last_validated_at?: string | null
          provider?: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          encrypted_key?: string
          key_last4?: string
          last_used_at?: string | null
          last_validated_at?: string | null
          provider?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_companies: {
        Row: {
          company_id: number
          end_date: string | null
          id: number
          is_current: boolean
          start_date: string | null
          title: string | null
          user_id: string
        }
        Insert: {
          company_id: number
          end_date?: string | null
          id?: number
          is_current?: boolean
          start_date?: string | null
          title?: string | null
          user_id: string
        }
        Update: {
          company_id?: number
          end_date?: string | null
          id?: number
          is_current?: boolean
          start_date?: string | null
          title?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_companies_company_fk"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_companies_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_milestones: {
        Row: {
          milestone: string
          reached_at: string
          user_id: string
        }
        Insert: {
          milestone: string
          reached_at?: string
          user_id: string
        }
        Update: {
          milestone?: string
          reached_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_milestones_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_schools: {
        Row: {
          degree: string | null
          end_year: number | null
          field_of_study: string | null
          id: number
          school_id: number
          start_year: number | null
          user_id: string
        }
        Insert: {
          degree?: string | null
          end_year?: number | null
          field_of_study?: string | null
          id?: number
          school_id: number
          start_year?: number | null
          user_id: string
        }
        Update: {
          degree?: string | null
          end_year?: number | null
          field_of_study?: string | null
          id?: number
          school_id?: number
          start_year?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_schools_school_fk"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_schools_user_fk"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          apify_enrichment_enabled: boolean
          created_at: string | null
          diff_analysis_enabled: boolean
          discovery_enabled: boolean
          dismissed_getting_started: string[]
          email: string | null
          extension_last_seen_at: string | null
          extension_onboarding_contact_id: number | null
          extension_onboarding_state: string
          first_name: string
          followup_nudges_enabled: boolean
          id: string
          last_name: string
          onboarding_state: string
          phone: string | null
          status: string
          updated_at: string | null
          web_last_seen_at: string | null
        }
        Insert: {
          apify_enrichment_enabled?: boolean
          created_at?: string | null
          diff_analysis_enabled?: boolean
          discovery_enabled?: boolean
          dismissed_getting_started?: string[]
          email?: string | null
          extension_last_seen_at?: string | null
          extension_onboarding_contact_id?: number | null
          extension_onboarding_state?: string
          first_name: string
          followup_nudges_enabled?: boolean
          id: string
          last_name: string
          onboarding_state?: string
          phone?: string | null
          status?: string
          updated_at?: string | null
          web_last_seen_at?: string | null
        }
        Update: {
          apify_enrichment_enabled?: boolean
          created_at?: string | null
          diff_analysis_enabled?: boolean
          discovery_enabled?: boolean
          dismissed_getting_started?: string[]
          email?: string | null
          extension_last_seen_at?: string | null
          extension_onboarding_contact_id?: number | null
          extension_onboarding_state?: string
          first_name?: string
          followup_nudges_enabled?: boolean
          id?: string
          last_name?: string
          onboarding_state?: string
          phone?: string | null
          status?: string
          updated_at?: string | null
          web_last_seen_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "users_extension_onboarding_contact_id_fkey"
            columns: ["extension_onboarding_contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      append_contact_note: {
        Args: { p_contact_id: number; p_note: string }
        Returns: undefined
      }
      apply_bundle_resolutions: { Args: { p_rows: Json }; Returns: number }
      bundle_alumni_stats: {
        Args: { p_bundle_id: number }
        Returns: {
          alumni_company_count: number
          alumni_count: number
          alumni_product_count: number
        }[]
      }
      bundle_company_stats: {
        Args: { p_bundle_id: number }
        Returns: {
          alumni_count: number
          company_id: number
          logo_url: string
          name: string
          product_alumni_count: number
          prospect_count: number
        }[]
      }
      bundle_visible_to: {
        Args: { p_bundle_id: number; p_user: string }
        Returns: boolean
      }
      delete_pipeline_cycle: {
        Args: { p_cycle_number: number; p_target_company_id: number }
        Returns: undefined
      }
      increment_ai_shared_usage: {
        Args: { p_cost: number; p_period_start: string; p_user_id: string }
        Returns: undefined
      }
      is_internal_email: { Args: { p_email: string }; Returns: boolean }
      latest_contact_snapshots: {
        Args: { p_contact_ids: number[] }
        Returns: {
          contact_id: number
          snapshot: Json
        }[]
      }
      network_tier_counts: {
        Args: never
        Returns: {
          active: number
          bench: number
          prospect: number
        }[]
      }
      replace_transcript_segments: {
        Args: { p_meeting_id: number; p_segments: Json }
        Returns: undefined
      }
      save_pipeline_cycle: {
        Args: {
          p_cycle_number: number
          p_payload: Json
          p_target_company_id: number
        }
        Returns: number
      }
      sum_scrape_spend: {
        Args: { p_since: string; p_user_id: string }
        Returns: number
      }
      sum_scrape_spend_mode: {
        Args: { p_mode: string; p_since: string; p_user_id: string }
        Returns: number
      }
      user_company_alumni_counts: {
        Args: never
        Returns: {
          alumni_count: number
          company_id: number
          product_alumni_count: number
        }[]
      }
      user_is_internal: { Args: { uid: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

