import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
    ],
    setupFiles: ['src/__tests__/setup.ts'],
    // CAR-186, CAR-208. Coverage here is a GATE, not a report: `npm run
    // test:coverage`, and the CI `web` job which runs the suite with
    // `--coverage`, fail on the thresholds below rather than printing a number
    // for someone to read. Two kinds of regression trip it, and they are not
    // interchangeable — see the note over `thresholds`.
    //
    // What it measures is scoped to the logic tiers on purpose.
    // `src/components` and `src/app` are deliberately NOT measured: a
    // line-coverage number on UI files rewards shallow render-and-assert-nothing
    // tests, which is the failure mode CAR-182 is moving away from. The browser
    // E2E tier (CAR-189) owns those.
    //
    // `src/mcp` IS measured, since CAR-208. It was outside `include` while
    // CAR-186's commit message asserted "only database.types.ts and test files
    // are excluded" — 15 modules and ~2,900 lines sitting at 47.07% statements /
    // 39.86% branches, with `src/mcp/tools` at 4.25% and several tools at 0%.
    // (15/2,896 is the MEASURED set. A first draft said 16/3,300, which counted
    // `__tests__/helpers/recording-client.ts` — a 437-line test helper that the
    // `exclude` below correctly drops, so the count and the percentage were
    // computed over different file sets.)
    // Nothing else covered the gap either: the `mcp` CI job is `tsc --noEmit`
    // only, and neither the integration nor the E2E tier references it. What
    // was missing was specifically a coverage FLOOR — no per-area budget, and
    // far too small a share of the corpus to move a global percentage — so a
    // new untested MCP tool moved no number and failed no check. It is a
    // shipped product surface, not a script.
    //
    // `include` is what makes this a gate rather than a report. Without it the v8
    // provider only reports files some test imported, so a brand-new untested
    // module is invisible and the percentage cannot move. With it, every matched
    // file is transformed and reported at 0% whether or not a test touched it.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: ['src/lib/**/*.{ts,tsx}', 'src/hooks/**/*.{ts,tsx}', 'src/mcp/**/*.{ts,tsx}'],
      exclude: [
        // Generated by `npm run gen:types` from the migration chain, and pinned
        // against drift by the types-drift CI job. Nothing here is hand-written.
        'src/lib/database.types.ts',
        // Vitest already drops the test files it collected; these are explicit so
        // the set stays right if a test ever lands beside its subject (as
        // src/lib/transcript-parser.test.ts does).
        '**/*.test.{ts,tsx}',
        '**/__tests__/**',
      ],
      // Two instruments, because they catch different regressions.
      //
      // The percentages are the anti-erosion floor: the suite as a whole cannot
      // drift down. They are ~2 points under the measured baseline so the gate
      // ratchets instead of failing on arrival.
      //
      // The negative numbers are Vitest's "maximum uncovered units" form (-N means
      // at most N uncovered), applied per area. They exist because a percentage
      // alone does not actually catch this ticket's stated failure mode: dropping
      // a 120-statement untested module into an 8,310-statement corpus moves the
      // global figure by under a point, so it sails past any sane floor. Against a
      // budget it is a hard fail. EVERY measured area carries its own budget
      // rather than only feeding the global percentages, because a weak area
      // blended into one number hides behind a strong one - which is exactly
      // what had happened to src/hooks, and to src/mcp before CAR-208. The
      // measured column below is where the spread between them is visible.
      //
      // Headroom is ~3% of each area's uncovered total. That is calibrated to pass
      // a well-tested feature (200 new statements at 85% adds 30 uncovered) and
      // fail an untested one (200 new statements adds 200). When a change is
      // legitimately worth the budget, raise the number in the same commit - the
      // failure message prints the exact figure to use.
      //
      // PLATFORM is a factor, by a little. The first CI run of the CAR-186
      // config (linux-x64) reported 68.38 / 61.21 / 65.41 / 71.44 against the
      // 68.37 / 61.31 / 65.41 / 71.43 measured on darwin-arm64. Statements,
      // functions and lines land within 0.01; branches is the loose one at 0.10,
      // roughly seven branches. So branches keeps the slackest floor, and no
      // threshold here should ever be tightened to within a fraction of a
      // measured value - leave room for the platform you did not measure on.
      //
      // RE-BASELINED 2026-07-25 (CAR-208), `npm run test:coverage` on
      // darwin-arm64. Folding src/mcp in costs the globals about two points -
      // measured, from the same run, lib+hooks alone come to
      // 69.18 / 61.86 / 66.41 / 72.25 against 67.35 / 60.12 / 64.35 / 70.45 with
      // src/mcp included. Left at the old floors that is a ~1.2 margin on
      // branches, so the floors move down with the measurement rather than
      // quietly eating the headroom the note above insists on.
      //
      // The per-area budgets are also re-measured, and src/hooks had drifted far
      // the OTHER way: it was documented at 24.94% and is now 39.30%, so its old
      // 330-statement budget authorized 69 uncovered statements of new debt. A
      // budget that loose is not a gate, and the stale comment beside it was its
      // own false claim.
      //
      // BRANCHES is a RANGE, not a point, and the table below records the low
      // end of the darwin range. Measured across six local runs and the CI run
      // for this commit: global branches is 60.12-60.14 on darwin-arm64 (4337
      // or 4338 of 7213 — it moves by one branch between otherwise identical
      // runs) and 60.03 on CI's linux/node22, where src/lib branches is 2420
      // uncovered against 2413 locally. Nearly the whole spread is one file,
      // `src/lib/scrape-mapper.ts` (202 branches, 187 covered on darwin, 180 on
      // linux). Statements, functions and lines agree within one unit and do
      // not drift run to run. Do NOT "correct" a branch figure to whatever your
      // machine printed this time; that is how a range gets rewritten as a
      // point, twice, in opposite directions.
      //
      // RE-MEASURED after merging main (CAR-205/206/207/212, 84 files under
      // src). Every figure below moved UP and no threshold needed to move: the
      // tightest headroom in any area is 16 units (src/mcp functions), against
      // the 30-unit calibration the note above names. Thresholds are unchanged
      // from the re-baseline; only the measured column is refreshed, because a
      // stale "measured" is the same false claim as a stale count anywhere else.
      //
      //                    measured        threshold
      //   global      stmt 68.19%          65
      //               brch 60.82%          58
      //               func 66.09%          62
      //               line 71.22%          68
      //   src/lib     stmt 71.15%  2303u   2375
      //               brch 63.17%  2404u   2485
      //               func 68.99%   382u    400
      //               line 74.30%  1745u   1800
      //   src/hooks   stmt 47.79%   236u    295
      //               brch 36.51%   120u    145
      //               func 54.87%    51u     72
      //               line 48.97%   198u    255
      //   src/mcp     stmt 48.99%   380u    430
      //               brch 41.52%   324u    368
      //               func 53.33%    84u    100
      //               line 52.11%   306u    345
      thresholds: {
        statements: 65,
        branches: 58,
        functions: 62,
        lines: 68,
        'src/lib/**': {
          // functions stays at -400 rather than the ~3% -391 the other three
          // use. 391 against 379 measured is 12 units, and the house data-layer
          // module shape spends that on its own: contacts.ts carries 21
          // uncovered functions, home.ts 16, meetings.ts 16, action-items.ts 14.
          // meetings.ts would fail on functions (16 > 12) while passing every
          // other metric, so functions alone would become the binding one for a
          // routine addition. src/lib's uncovered function count is a few
          // hundred, which is the small-N regime the src/mcp note below
          // describes — it just arrives here per-metric rather than per-area.
          statements: -2375,
          branches: -2485,
          functions: -400,
          lines: -1800,
        },
        // Loosened from the first cut of this re-baseline (-285/-138/-65/-245),
        // which overshot. The comment above states the calibration in ABSOLUTE
        // units — "200 new statements at 85% adds 30 uncovered" must pass — and
        // -285 against 261 measured leaves 24, so the file's own named pass case
        // failed this area's gate. Four of the nine files already in src/hooks
        // would each, alone, have exceeded it. Percentage headroom is the wrong
        // instrument on a few hundred units; the 30-unit calibration binds.
        'src/hooks/**': {
          statements: -295,
          branches: -145,
          functions: -72,
          lines: -255,
        },
        // Its own budget, not folded into the globals alone: src/mcp sits with
        // src/hooks well under src/lib on every metric (the two are within a
        // few points of each other, 14 to 27 below src/lib - see the table
        // above), and a single blended number would let it hide behind src/lib
        // exactly as hooks did. Headroom is wider in
        // relative terms than src/lib's ~3% for the same reason hooks' is - on a
        // few hundred units, 3% is single digits and any real feature trips it.
        'src/mcp/**': {
          statements: -430,
          branches: -368,
          functions: -100,
          lines: -345,
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@ext': path.resolve(__dirname, '../chrome-extension/src'),
      '@panel': path.resolve(__dirname, '../chrome-extension/panel-app/src'),
      // `server-only` (CAR-158/F39) resolves to a module that THROWS unless the
      // importer sits in React's server layer: its exports map is
      // { "react-server": empty.js, default: index.js } and index.js throws on
      // sight. Next satisfies that condition itself; Vitest does not, so
      // without this every test touching a fenced module dies at import.
      //
      // Alias rather than conditions, deliberately. Setting
      // `ssr.resolve.conditions: ['react-server']` does silence server-only,
      // but the same condition redirects `react-dom/client` to its RSC stub
      // ("react-dom/client is not supported in React Server Components"),
      // which breaks all 30 React component test files. Aliasing the one
      // package to its own no-op entry point is surgical: it leaves every
      // other package's condition resolution untouched.
      'server-only': path.resolve(__dirname, './node_modules/server-only/empty.js'),
    },
  },
});
