import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
    ],
    setupFiles: ['src/__tests__/setup.ts'],
    // CAR-186, CAR-208. Coverage is scoped to the logic tiers on purpose.
    // `src/components` and `src/app` are deliberately NOT measured: a
    // line-coverage number on UI files rewards shallow render-and-assert-nothing
    // tests, which is the failure mode CAR-182 is moving away from. The browser
    // E2E tier (CAR-189) owns those.
    //
    // `src/mcp` IS measured, since CAR-208. It was outside `include` while
    // CAR-186's commit message asserted "only database.types.ts and test files
    // are excluded" — 16 modules and ~3,300 lines sitting at 47.07% statements /
    // 39.86% branches, with `src/mcp/tools` at 4.25% and several tools at 0%.
    // Nothing else covered the gap either: the `mcp` CI job is `tsc --noEmit`
    // only, and neither the integration nor the E2E tier references it, so a new
    // untested MCP tool moved no number and failed no check. It is a shipped
    // product surface, not a script.
    //
    // `include` is what makes this a gate rather than a report. Without it the v8
    // provider only reports files some test imported, so a brand-new untested
    // module is invisible and the percentage cannot move. With it, every matched
    // file is transformed and reported at 0% whether or not a test touched it.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: ['src/lib/**/*.{ts,tsx}', 'src/hooks/**/*.{ts,tsx}', 'src/mcp/**/*.{ts,tsx}'],
      exclude: [
        // Generated by `npm run gen:types` from the migration chain, and pinned
        // against drift by the types-drift CI job. Nothing here is hand-written.
        'src/lib/database.types.ts',
        // Vitest already drops the test files it collected; these are explicit so
        // the set stays right if a test ever lands beside its subject (as
        // src/lib/transcript-parser.test.ts does).
        '**/*.test.{ts,tsx}',
        '**/__tests__/**',
      ],
      // Two instruments, because they catch different regressions.
      //
      // The percentages are the anti-erosion floor: the suite as a whole cannot
      // drift down. They are ~2 points under the measured baseline so the gate
      // ratchets instead of failing on arrival.
      //
      // The negative numbers are Vitest's "maximum uncovered units" form (-N means
      // at most N uncovered), applied per area. They exist because a percentage
      // alone does not actually catch this ticket's stated failure mode: dropping
      // a 120-statement untested module into an 8,310-statement corpus moves the
      // global figure by under a point, so it sails past any sane floor. Against a
      // budget it is a hard fail. The budgets are split lib/hooks so a weak area
      // cannot hide behind a strong one - hooks sit at 25%, and blending that into
      // one number would bury it.
      //
      // Headroom is ~3% of each area's uncovered total. That is calibrated to pass
      // a well-tested feature (200 new statements at 85% adds 30 uncovered) and
      // fail an untested one (200 new statements adds 200). When a change is
      // legitimately worth the budget, raise the number in the same commit - the
      // failure message prints the exact figure to use.
      //
      // PLATFORM is a factor, by a little. The first CI run of the CAR-186
      // config (linux-x64) reported 68.38 / 61.21 / 65.41 / 71.44 against the
      // 68.37 / 61.31 / 65.41 / 71.43 measured on darwin-arm64. Statements,
      // functions and lines land within 0.01; branches is the loose one at 0.10,
      // roughly seven branches. So branches keeps the slackest floor, and no
      // threshold here should ever be tightened to within a fraction of a
      // measured value - leave room for the platform you did not measure on.
      //
      // RE-BASELINED 2026-07-25 (CAR-208), `npm run test:coverage` on
      // darwin-arm64. Folding src/mcp in costs the globals about two points -
      // measured, from the same run, lib+hooks alone come to
      // 69.18 / 61.86 / 66.41 / 72.25 against 67.35 / 60.14 / 64.35 / 70.45 with
      // src/mcp included. Left at the old floors that is a ~1.2 margin on
      // branches, so the floors move down with the measurement rather than
      // quietly eating the headroom the note above insists on.
      //
      // The per-area budgets are also re-measured, and src/hooks had drifted far
      // the OTHER way: it was documented at 24.94% and is now 39.30%, so its old
      // 330-statement budget authorized 69 uncovered statements of new debt. A
      // budget that loose is not a gate, and the stale comment beside it was its
      // own false claim.
      //
      //                    measured        threshold
      //   global      stmt 67.35%          65
      //               brch 60.14%          58
      //               func 64.35%          62
      //               line 70.45%          68
      //   src/lib     stmt 70.81%  2305u   2375
      //               brch 62.75%  2412u   2485
      //               func 68.31%   379u    391
      //               line 74.03%  1746u   1800
      //   src/hooks   stmt 39.30%   261u    285
      //               brch 28.57%   125u    138
      //               func 45.37%    59u     65
      //               line 40.16%   222u    245
      //   src/mcp     stmt 47.07%   397u    430
      //               brch 39.86%   338u    368
      //               func 49.44%    91u    100
      //               line 50.62%   318u    345
      thresholds: {
        statements: 65,
        branches: 58,
        functions: 62,
        lines: 68,
        'src/lib/**': {
          statements: -2375,
          branches: -2485,
          functions: -391,
          lines: -1800,
        },
        'src/hooks/**': {
          statements: -285,
          branches: -138,
          functions: -65,
          lines: -245,
        },
        // Its own budget, not folded into the globals alone: src/mcp is the
        // weakest area by a wide margin and a single blended number would let it
        // hide behind src/lib exactly as hooks did. Headroom is wider in
        // relative terms than src/lib's ~3% for the same reason hooks' is - on a
        // few hundred units, 3% is single digits and any real feature trips it.
        'src/mcp/**': {
          statements: -430,
          branches: -368,
          functions: -100,
          lines: -345,
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@ext': path.resolve(__dirname, '../chrome-extension/src'),
      '@panel': path.resolve(__dirname, '../chrome-extension/panel-app/src'),
      // `server-only` (CAR-158/F39) resolves to a module that THROWS unless the
      // importer sits in React's server layer: its exports map is
      // { "react-server": empty.js, default: index.js } and index.js throws on
      // sight. Next satisfies that condition itself; Vitest does not, so
      // without this every test touching a fenced module dies at import.
      //
      // Alias rather than conditions, deliberately. Setting
      // `ssr.resolve.conditions: ['react-server']` does silence server-only,
      // but the same condition redirects `react-dom/client` to its RSC stub
      // ("react-dom/client is not supported in React Server Components"),
      // which breaks all 30 React component test files. Aliasing the one
      // package to its own no-op entry point is surgical: it leaves every
      // other package's condition resolution untouched.
      'server-only': path.resolve(__dirname, './node_modules/server-only/empty.js'),
    },
  },
});
