import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
    ],
    setupFiles: ['src/__tests__/setup.ts'],
    // CAR-186. Coverage is scoped to the logic tiers on purpose. `src/components`
    // and `src/app` are deliberately NOT measured: a line-coverage number on UI
    // files rewards shallow render-and-assert-nothing tests, which is the failure
    // mode CAR-182 is moving away from. The browser E2E tier (CAR-189) owns those.
    //
    // `include` is what makes this a gate rather than a report. Without it the v8
    // provider only reports files some test imported, so a brand-new untested
    // module is invisible and the percentage cannot move. With it, every matched
    // file is transformed and reported at 0% whether or not a test touched it.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: ['src/lib/**/*.{ts,tsx}', 'src/hooks/**/*.{ts,tsx}'],
      exclude: [
        // Generated by `npm run gen:types` from the migration chain, and pinned
        // against drift by the types-drift CI job. Nothing here is hand-written.
        'src/lib/database.types.ts',
        // Vitest already drops the test files it collected; these are explicit so
        // the set stays right if a test ever lands beside its subject (as
        // src/lib/transcript-parser.test.ts does).
        '**/*.test.{ts,tsx}',
        '**/__tests__/**',
      ],
      // Two instruments, because they catch different regressions.
      //
      // The percentages are the anti-erosion floor: the suite as a whole cannot
      // drift down. They are ~2 points under the measured baseline so the gate
      // ratchets instead of failing on arrival.
      //
      // The negative numbers are Vitest's "maximum uncovered units" form (-N means
      // at most N uncovered), applied per area. They exist because a percentage
      // alone does not actually catch this ticket's stated failure mode: dropping
      // a 120-statement untested module into an 8,310-statement corpus moves the
      // global figure by under a point, so it sails past any sane floor. Against a
      // budget it is a hard fail. The budgets are split lib/hooks so a weak area
      // cannot hide behind a strong one - hooks sit at 25%, and blending that into
      // one number would bury it.
      //
      // Headroom is ~3% of each area's uncovered total. That is calibrated to pass
      // a well-tested feature (200 new statements at 85% adds 30 uncovered) and
      // fail an untested one (200 new statements adds 200). When a change is
      // legitimately worth the budget, raise the number in the same commit - the
      // failure message prints the exact figure to use.
      //
      // BASELINE MEASURED 2026-07-24 on this branch, `npm run test:coverage`,
      // 249 files / 2,363 tests / 165 source files. Node version is not a factor:
      // Node 22 and Node 26 agree byte for byte on one machine, and four runs are
      // stable except branches, which drifts +/-1 locally.
      //
      // PLATFORM is a factor, by a little. The first CI run of this config
      // (linux-x64) reported 68.38 / 61.21 / 65.41 / 71.44 against the
      // 68.37 / 61.31 / 65.41 / 71.43 measured on darwin-arm64. Statements,
      // functions and lines land within 0.01; branches is the loose one at 0.10,
      // roughly seven branches. So branches keeps the slackest floor, and no
      // threshold here should ever be tightened to within a fraction of a
      // measured value - leave room for the platform you did not measure on.
      //
      //                    measured        threshold
      //   global      stmt 68.37%          66
      //               brch 61.31%          59
      //               func 65.41%          63
      //               line 71.43%          69
      //   src/lib     stmt 70.62%  2321u   2400
      //               brch 62.49%  2427u   2500
      //               func 68.09%   382u    400
      //               line 73.83%  1760u   1830
      //   src/hooks   stmt 24.94%   307u    330
      //               brch 16.57%   141u    160
      //               func 35.51%    69u     75
      //               line 25.78%   262u    285
      thresholds: {
        statements: 66,
        branches: 59,
        functions: 63,
        lines: 69,
        'src/lib/**': {
          statements: -2400,
          branches: -2500,
          functions: -400,
          lines: -1830,
        },
        'src/hooks/**': {
          statements: -330,
          branches: -160,
          functions: -75,
          lines: -285,
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@ext': path.resolve(__dirname, '../chrome-extension/src'),
      '@panel': path.resolve(__dirname, '../chrome-extension/panel-app/src'),
      // `server-only` (CAR-158/F39) resolves to a module that THROWS unless the
      // importer sits in React's server layer: its exports map is
      // { "react-server": empty.js, default: index.js } and index.js throws on
      // sight. Next satisfies that condition itself; Vitest does not, so
      // without this every test touching a fenced module dies at import.
      //
      // Alias rather than conditions, deliberately. Setting
      // `ssr.resolve.conditions: ['react-server']` does silence server-only,
      // but the same condition redirects `react-dom/client` to its RSC stub
      // ("react-dom/client is not supported in React Server Components"),
      // which breaks all 30 React component test files. Aliasing the one
      // package to its own no-op entry point is surgical: it leaves every
      // other package's condition resolution untouched.
      'server-only': path.resolve(__dirname, './node_modules/server-only/empty.js'),
    },
  },
});
