#!/usr/bin/env bash
set -euo pipefail

# Regenerates careervine/src/lib/database.types.ts from the local migration chain.
#
# The generated file is the single source of truth for Supabase types (CAR-142).
# It is produced by applying every migration in supabase/migrations/ to a fresh
# local Postgres and introspecting the result, so it can never drift from the
# migrations. CI runs this same script and fails if the committed file differs
# (see the `types-drift` job in .github/workflows/ci.yml), which forces any
# migration PR to regenerate types.
#
# Prereq: a local Supabase stack at the current migration chain must be running.
#   supabase db reset   # rebuild the local DB from supabase/migrations/*, then:
#   npm run gen:types    # (from careervine/) or: ./scripts/gen-supabase-types.sh
#
# The header below is emitted by this script (not by `supabase gen types`), so
# the committed file stays byte-identical to what CI regenerates.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="careervine/src/lib/database.types.ts"

# The CI `types-drift` job pins this exact CLI version; the committed file must
# be byte-identical to its output. A different local CLI can produce a
# byte-different (but still correct) file that turns CI red, so warn early.
EXPECTED_CLI="2.109.1"
actual_cli="$(supabase --version 2>/dev/null)"
if [[ "$actual_cli" != *"$EXPECTED_CLI"* ]]; then
  echo "Warning: supabase CLI is '${actual_cli:-unknown}', but the committed types + CI expect $EXPECTED_CLI." >&2
  echo "         A version mismatch can generate a byte-different file that fails the CI types-drift job." >&2
fi

if ! supabase status >/dev/null 2>&1; then
  echo "Error: local Supabase stack is not running." >&2
  echo "Start it and rebuild from migrations first:  supabase start && supabase db reset" >&2
  exit 1
fi

# Types come from the CURRENT local schema, not the migration files directly. If
# migrations changed since the stack was last built, run `supabase db reset`
# first or the generated types will silently reflect stale schema.
echo "Generating from the running local stack's current schema (run 'supabase db reset' first if migrations changed)." >&2

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'EOF'
// AUTO-GENERATED by `npm run gen:types` (CAR-142). DO NOT EDIT BY HAND.
// Source of truth: supabase/migrations/*. Regenerate after any migration change.
// Per-table / per-column prose lives in supabase/database-reference/schema-notes.md.
// Hand-authored app-level types (OnboardingState, ...) live in src/lib/app-types.ts.

EOF
  supabase gen types typescript --local
} >"$tmp"

mv "$tmp" "$OUT"
trap - EXIT
echo "Wrote $OUT"
