-- Plan 41 (CAR-29): discovery feed — new PM hires at target companies.
--
-- A weekly cron searches LinkedIn (harvestapi/linkedin-profile-search, Short
-- mode, $0.10/page) per high-priority target company for PMs who joined in
-- the last 90 days. Results are strangers, deduped against contacts and
-- suppressed_imports, surfaced as discovery_candidates for one-click
-- add-as-prospect or dismiss.

-- 1. Admin kill switch: discovery is NEW paid spend, so unlike the CAR-25
--    controls it defaults OFF — the admin dashboard enables it per account.
ALTER TABLE users ADD COLUMN discovery_enabled boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN users.discovery_enabled IS 'Admin switch for the weekly discovery feed (paid LinkedIn people-search per target company). Default off; writable only by the service role.';

-- Self-escalation guard, same two layers as the CAR-25 columns:
-- 1. Column privileges: the authenticated GRANT lists profile columns only,
--    so the new column is already un-updatable by users. (No change.)
-- 2. Belt-and-suspenders: pin it in the self-update policy's WITH CHECK.
--    NOTE: DROP+CREATE — every previously pinned column must be re-listed.
DROP POLICY IF EXISTS "users_update_own" ON users;
CREATE POLICY "users_update_own" ON users
  FOR UPDATE USING (id = auth.uid())
  WITH CHECK (
    id = auth.uid()
    AND status = (SELECT u.status FROM users u WHERE u.id = auth.uid())
    AND apify_enrichment_enabled = (SELECT u.apify_enrichment_enabled FROM users u WHERE u.id = auth.uid())
    AND diff_analysis_enabled = (SELECT u.diff_analysis_enabled FROM users u WHERE u.id = auth.uid())
    AND discovery_enabled = (SELECT u.discovery_enabled FROM users u WHERE u.id = auth.uid())
  );

-- 2. Candidate pool: one row per (user, canonical linkedin_url) ever seen by
--    discovery. Dismiss is sticky — re-discovery bumps last_seen_at but never
--    resurrects status.
CREATE TABLE IF NOT EXISTS discovery_candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id int NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  linkedin_url text NOT NULL,
  public_identifier text,
  name text NOT NULL,
  headline text,
  location text,
  photo_url text,
  position text,
  raw jsonb NOT NULL,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'added', 'dismissed')),
  added_contact_id int REFERENCES contacts(id) ON DELETE SET NULL,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, linkedin_url)
);

COMMENT ON TABLE discovery_candidates IS 'Discovery-feed candidates (plan 41): strangers found by the weekly target-company people search. linkedin_url is canonical. status: new = awaiting review, added = converted to a contact, dismissed = never show again.';
COMMENT ON COLUMN discovery_candidates.position IS 'Current title at the target company, when the short profile carries one.';

CREATE INDEX IF NOT EXISTS discovery_candidates_user_status_idx
  ON discovery_candidates (user_id, status);
CREATE INDEX IF NOT EXISTS discovery_candidates_user_company_status_idx
  ON discovery_candidates (user_id, company_id, status);

ALTER TABLE discovery_candidates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "discovery_candidates_select_own" ON discovery_candidates
  FOR SELECT USING (user_id = auth.uid());
-- Inserts/updates happen through the service client (cron ingest + the
-- add/dismiss API routes), so no user-facing insert/update policy.

-- 3. Rotation cursor: the weekly cron queries the stalest targeted companies
--    first. Stamped per company (all scoped rows together) at trigger time.
ALTER TABLE target_companies ADD COLUMN IF NOT EXISTS last_discovery_at timestamptz;

COMMENT ON COLUMN target_companies.last_discovery_at IS 'When the discovery cron last queried this company for new hires (plan 41). Stamped at run trigger, not ingest.';

-- 4. scrape_runs: discovery runs live in the same ledger so spend is one
--    number. company_id links a discovery run to the company it queried
--    (also backs the one-pending-per-company in-flight guard).
ALTER TABLE scrape_runs ADD COLUMN IF NOT EXISTS company_id int REFERENCES companies(id);

COMMENT ON COLUMN scrape_runs.company_id IS 'For discovery-mode runs: the company whose new hires this run searched (plan 41). NULL for contact-scrape runs.';

-- Atomic one-pending-discovery-per-company guard, same TOCTOU-proof shape as
-- scrape_runs_one_pending_per_contact: a concurrent duplicate insert fails
-- instead of starting a second paid search.
CREATE UNIQUE INDEX IF NOT EXISTS scrape_runs_one_pending_discovery_per_company
  ON scrape_runs (user_id, company_id)
  WHERE status = 'pending' AND mode = 'discovery' AND company_id IS NOT NULL;

ALTER TABLE scrape_runs DROP CONSTRAINT IF EXISTS scrape_runs_mode_check;
ALTER TABLE scrape_runs ADD CONSTRAINT scrape_runs_mode_check
  CHECK (mode IN ('profile', 'email', 'resolve', 'discovery'));

ALTER TABLE scrape_runs DROP CONSTRAINT IF EXISTS scrape_runs_trigger_check;
ALTER TABLE scrape_runs ADD CONSTRAINT scrape_runs_trigger_check
  CHECK (trigger IN ('manual', 'enrich_on_save', 'cadence', 'discovery'));

COMMENT ON COLUMN scrape_runs.mode IS 'profile = $0.004 profile-only; email = $0.01 profile + email search; resolve = $0.004 name-search page; discovery = $0.10 people-search page';
COMMENT ON COLUMN scrape_runs.trigger IS 'manual = per-contact button; enrich_on_save = extension save; cadence = daily drip cron; discovery = weekly new-hire search cron';

-- 5. Mode-filtered spend sum: powers the discovery soft cap and lets the
--    cadence soft-cap computation subtract discovery spend so the two lanes
--    have independent soft budgets (the $10 hard cap stays global-total).
CREATE OR REPLACE FUNCTION sum_scrape_spend_mode(p_user_id uuid, p_since timestamptz, p_mode text)
RETURNS numeric
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(SUM(cost_usd), 0)::numeric
  FROM scrape_runs
  WHERE user_id = p_user_id AND created_at >= p_since AND mode = p_mode;
$$;
