-- ═══════════════════════════════════════════════════════════════════
-- CAR-6: promote the pipeline preview to the production company page.
--
-- 1. target_companies becomes the SCOPE table (§18.2.1 / §21.4 of plan 35):
--    location_id NULL = company-wide scope, non-NULL = office scope.
--    is_targeted is a soft flag so un-targeting never destroys pipeline data.
-- 2. pipeline_cycles + four child tables persist the recruiting pipeline
--    that the preview kept in localStorage.
-- 3. save/delete RPCs keep cycle writes atomic (and renumbering safe).
-- 4. Private storage bucket for application PDFs (resume / cover letter).
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. target_companies → scoped targets ────────────────────────────

ALTER TABLE target_companies
  ADD COLUMN IF NOT EXISTS location_id int REFERENCES locations(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS is_targeted boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS active_cycle int NOT NULL DEFAULT 1;

COMMENT ON COLUMN target_companies.location_id IS 'NULL = company-wide scope; set = office-scoped target (one pipeline per scope)';
COMMENT ON COLUMN target_companies.is_targeted IS 'Soft targeting flag — false keeps the row (and its pipeline cycles) while removing it from target views';
COMMENT ON COLUMN target_companies.active_cycle IS 'Which pipeline cycle the user last worked in for this scope (UI continuity)';

ALTER TABLE target_companies
  DROP CONSTRAINT IF EXISTS target_companies_user_id_company_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS target_companies_user_company_companywide
  ON target_companies (user_id, company_id)
  WHERE location_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS target_companies_user_company_location
  ON target_companies (user_id, company_id, location_id)
  WHERE location_id IS NOT NULL;

-- ── 2. pipeline_cycles ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pipeline_cycles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_company_id int NOT NULL REFERENCES target_companies(id) ON DELETE CASCADE,
  cycle_number int NOT NULL,
  selected_stage text NOT NULL DEFAULT 'researching'
    CHECK (selected_stage IN ('researching', 'outreach_active', 'applied', 'interviewing', 'closed')),
  declined_next_cycle boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  -- Not deferrable: ON CONFLICT in save_pipeline_cycle needs it as an
  -- arbiter. delete_pipeline_cycle renumbers via a sign-flip instead.
  CONSTRAINT pipeline_cycles_scope_number_key UNIQUE (target_company_id, cycle_number)
);

COMMENT ON TABLE pipeline_cycles IS 'One application cycle per target scope (company-wide or office); the recruiting pipeline the company page renders';

CREATE INDEX IF NOT EXISTS pipeline_cycles_target_idx ON pipeline_cycles (target_company_id);

-- ── 2a. Cycle children (uuid PKs are client-generated so upserts work) ──

CREATE TABLE IF NOT EXISTS pipeline_programs (
  id uuid PRIMARY KEY,
  cycle_id int NOT NULL REFERENCES pipeline_cycles(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  apps_open text NOT NULL DEFAULT '',
  job_potential text NOT NULL DEFAULT '',
  position int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN pipeline_programs.apps_open IS 'Free text or "date:YYYY-MM-DD" sentinel, matching the preview''s researching-program editor';

CREATE TABLE IF NOT EXISTS pipeline_notes (
  id uuid PRIMARY KEY,
  cycle_id int NOT NULL REFERENCES pipeline_cycles(id) ON DELETE CASCADE,
  body text NOT NULL DEFAULT '',
  position int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pipeline_applications (
  id uuid PRIMARY KEY,
  cycle_id int NOT NULL REFERENCES pipeline_cycles(id) ON DELETE CASCADE,
  job_title text NOT NULL DEFAULT '',
  location text NOT NULL DEFAULT '',
  date_applied date,
  resume_path text,
  resume_name text,
  resume_size_bytes int,
  cover_letter_path text,
  cover_letter_name text,
  cover_letter_size_bytes int,
  position int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN pipeline_applications.resume_path IS 'Storage object path in the application-files bucket ({user_id}/{uuid}.pdf)';

CREATE TABLE IF NOT EXISTS pipeline_interview_rounds (
  id uuid PRIMARY KEY,
  cycle_id int NOT NULL REFERENCES pipeline_cycles(id) ON DELETE CASCADE,
  interview_date date,
  interviewer text NOT NULL DEFAULT '',
  questions text NOT NULL DEFAULT '',
  position int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pipeline_programs_cycle_idx ON pipeline_programs (cycle_id);
CREATE INDEX IF NOT EXISTS pipeline_notes_cycle_idx ON pipeline_notes (cycle_id);
CREATE INDEX IF NOT EXISTS pipeline_applications_cycle_idx ON pipeline_applications (cycle_id);
CREATE INDEX IF NOT EXISTS pipeline_interview_rounds_cycle_idx ON pipeline_interview_rounds (cycle_id);

-- ── 2b. RLS — ownership chained through target_companies.user_id ────

ALTER TABLE pipeline_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_interview_rounds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "pipeline_cycles_all_own" ON pipeline_cycles
  FOR ALL USING (
    target_company_id IN (SELECT id FROM target_companies WHERE user_id = auth.uid())
  ) WITH CHECK (
    target_company_id IN (SELECT id FROM target_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "pipeline_programs_all_own" ON pipeline_programs
  FOR ALL USING (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  ) WITH CHECK (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  );

CREATE POLICY "pipeline_notes_all_own" ON pipeline_notes
  FOR ALL USING (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  ) WITH CHECK (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  );

CREATE POLICY "pipeline_applications_all_own" ON pipeline_applications
  FOR ALL USING (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  ) WITH CHECK (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  );

CREATE POLICY "pipeline_interview_rounds_all_own" ON pipeline_interview_rounds
  FOR ALL USING (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  ) WITH CHECK (
    cycle_id IN (
      SELECT pc.id FROM pipeline_cycles pc
      JOIN target_companies tc ON tc.id = pc.target_company_id
      WHERE tc.user_id = auth.uid()
    )
  );

-- ── 3. RPCs ─────────────────────────────────────────────────────────

-- Atomic upsert of a full cycle: cycle row + replace-sync of all four
-- child collections. SECURITY INVOKER — RLS above enforces ownership.
CREATE OR REPLACE FUNCTION save_pipeline_cycle(
  p_target_company_id int,
  p_cycle_number int,
  p_payload jsonb
) RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
  v_cycle_id int;
BEGIN
  INSERT INTO pipeline_cycles (target_company_id, cycle_number, selected_stage, declined_next_cycle, updated_at)
  VALUES (
    p_target_company_id,
    p_cycle_number,
    COALESCE(p_payload->>'selected_stage', 'researching'),
    COALESCE((p_payload->>'declined_next_cycle')::boolean, false),
    now()
  )
  ON CONFLICT (target_company_id, cycle_number) DO UPDATE SET
    selected_stage = EXCLUDED.selected_stage,
    declined_next_cycle = EXCLUDED.declined_next_cycle,
    updated_at = now()
  RETURNING id INTO v_cycle_id;

  -- programs
  DELETE FROM pipeline_programs
  WHERE cycle_id = v_cycle_id
    AND id NOT IN (SELECT (e->>'id')::uuid FROM jsonb_array_elements(COALESCE(p_payload->'programs', '[]'::jsonb)) e);
  INSERT INTO pipeline_programs (id, cycle_id, name, apps_open, job_potential, position)
  SELECT (e->>'id')::uuid, v_cycle_id,
         COALESCE(e->>'name', ''), COALESCE(e->>'apps_open', ''), COALESCE(e->>'job_potential', ''),
         ord - 1
  FROM jsonb_array_elements(COALESCE(p_payload->'programs', '[]'::jsonb)) WITH ORDINALITY AS t(e, ord)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, apps_open = EXCLUDED.apps_open,
    job_potential = EXCLUDED.job_potential, position = EXCLUDED.position;

  -- notes
  DELETE FROM pipeline_notes
  WHERE cycle_id = v_cycle_id
    AND id NOT IN (SELECT (e->>'id')::uuid FROM jsonb_array_elements(COALESCE(p_payload->'notes', '[]'::jsonb)) e);
  INSERT INTO pipeline_notes (id, cycle_id, body, position)
  SELECT (e->>'id')::uuid, v_cycle_id, COALESCE(e->>'body', ''), ord - 1
  FROM jsonb_array_elements(COALESCE(p_payload->'notes', '[]'::jsonb)) WITH ORDINALITY AS t(e, ord)
  ON CONFLICT (id) DO UPDATE SET body = EXCLUDED.body, position = EXCLUDED.position;

  -- applications
  DELETE FROM pipeline_applications
  WHERE cycle_id = v_cycle_id
    AND id NOT IN (SELECT (e->>'id')::uuid FROM jsonb_array_elements(COALESCE(p_payload->'applications', '[]'::jsonb)) e);
  INSERT INTO pipeline_applications (
    id, cycle_id, job_title, location, date_applied,
    resume_path, resume_name, resume_size_bytes,
    cover_letter_path, cover_letter_name, cover_letter_size_bytes, position
  )
  SELECT (e->>'id')::uuid, v_cycle_id,
         COALESCE(e->>'job_title', ''), COALESCE(e->>'location', ''),
         NULLIF(e->>'date_applied', '')::date,
         e->>'resume_path', e->>'resume_name', (e->>'resume_size_bytes')::int,
         e->>'cover_letter_path', e->>'cover_letter_name', (e->>'cover_letter_size_bytes')::int,
         ord - 1
  FROM jsonb_array_elements(COALESCE(p_payload->'applications', '[]'::jsonb)) WITH ORDINALITY AS t(e, ord)
  ON CONFLICT (id) DO UPDATE SET
    job_title = EXCLUDED.job_title, location = EXCLUDED.location,
    date_applied = EXCLUDED.date_applied,
    resume_path = EXCLUDED.resume_path, resume_name = EXCLUDED.resume_name,
    resume_size_bytes = EXCLUDED.resume_size_bytes,
    cover_letter_path = EXCLUDED.cover_letter_path, cover_letter_name = EXCLUDED.cover_letter_name,
    cover_letter_size_bytes = EXCLUDED.cover_letter_size_bytes,
    position = EXCLUDED.position;

  -- interview rounds
  DELETE FROM pipeline_interview_rounds
  WHERE cycle_id = v_cycle_id
    AND id NOT IN (SELECT (e->>'id')::uuid FROM jsonb_array_elements(COALESCE(p_payload->'interview_rounds', '[]'::jsonb)) e);
  INSERT INTO pipeline_interview_rounds (id, cycle_id, interview_date, interviewer, questions, position)
  SELECT (e->>'id')::uuid, v_cycle_id,
         NULLIF(e->>'interview_date', '')::date,
         COALESCE(e->>'interviewer', ''), COALESCE(e->>'questions', ''),
         ord - 1
  FROM jsonb_array_elements(COALESCE(p_payload->'interview_rounds', '[]'::jsonb)) WITH ORDINALITY AS t(e, ord)
  ON CONFLICT (id) DO UPDATE SET
    interview_date = EXCLUDED.interview_date, interviewer = EXCLUDED.interviewer,
    questions = EXCLUDED.questions, position = EXCLUDED.position;

  RETURN v_cycle_id;
END;
$$;

REVOKE ALL ON FUNCTION save_pipeline_cycle FROM PUBLIC;
GRANT EXECUTE ON FUNCTION save_pipeline_cycle TO authenticated;

-- Delete a cycle and renumber the ones above it; keeps active_cycle valid.
CREATE OR REPLACE FUNCTION delete_pipeline_cycle(
  p_target_company_id int,
  p_cycle_number int
) RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM pipeline_cycles
  WHERE target_company_id = p_target_company_id AND cycle_number = p_cycle_number;

  -- Renumber without transient unique violations: park the higher cycles
  -- on negative numbers, then land them one lower than they started.
  UPDATE pipeline_cycles
  SET cycle_number = -cycle_number
  WHERE target_company_id = p_target_company_id AND cycle_number > p_cycle_number;

  UPDATE pipeline_cycles
  SET cycle_number = -cycle_number - 1
  WHERE target_company_id = p_target_company_id AND cycle_number < 0;

  UPDATE target_companies
  SET active_cycle = GREATEST(1, LEAST(
        active_cycle - CASE WHEN active_cycle >= p_cycle_number THEN 1 ELSE 0 END,
        GREATEST((SELECT COALESCE(MAX(cycle_number), 1) FROM pipeline_cycles WHERE target_company_id = p_target_company_id), 1)
      ))
  WHERE id = p_target_company_id;
END;
$$;

REVOKE ALL ON FUNCTION delete_pipeline_cycle FROM PUBLIC;
GRANT EXECUTE ON FUNCTION delete_pipeline_cycle TO authenticated;

-- ── 4. Storage bucket for application PDFs ──────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('application-files', 'application-files', false, 5242880, ARRAY['application/pdf'])
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "application_files_select_own"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'application-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "application_files_insert_own"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'application-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "application_files_update_own"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'application-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "application_files_delete_own"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'application-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
