-- Plan 29 (CAR-15) phase 1: scrape_runs ledger + per-contact scrape failure tracking.
--
-- Apify actor runs are asynchronous (minutes), but serverless routes cap at
-- 60s. The trigger route records a pending scrape_runs row and starts the run
-- with a completion webhook; the callback route ingests when the run finishes.
-- The ledger is the source of truth for three things:
--   1. Idempotency — a QStash/webhook retry finds the pending row and does not
--      start a second paid run.
--   2. Spend accounting — sum(cost_usd) over the month enforces the hard cap
--      and feeds the Settings spend display.
--   3. Debuggability — every scrape is traceable to its Apify run.

CREATE TABLE IF NOT EXISTS scrape_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  apify_run_id text,
  actor text NOT NULL,
  mode text NOT NULL CHECK (mode IN ('profile', 'email')),
  trigger text NOT NULL CHECK (trigger IN ('manual', 'enrich_on_save', 'cadence')),
  contact_ids INT[] NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed', 'timed_out')),
  cost_usd numeric(10, 4) NOT NULL DEFAULT 0,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  UNIQUE (apify_run_id)
);

COMMENT ON TABLE scrape_runs IS 'Ledger of Apify scrape runs (plan 29). One row per run: idempotency guard, monthly spend accounting, and audit trail. Only succeeded rows carry a real cost_usd.';
COMMENT ON COLUMN scrape_runs.mode IS 'profile = $0.004 profile-only; email = $0.01 profile + email search';
COMMENT ON COLUMN scrape_runs.trigger IS 'manual = per-contact button; enrich_on_save = extension save; cadence = daily drip cron';

CREATE INDEX IF NOT EXISTS scrape_runs_user_status_idx ON scrape_runs (user_id, status);
CREATE INDEX IF NOT EXISTS scrape_runs_user_created_idx ON scrape_runs (user_id, created_at);

ALTER TABLE scrape_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "scrape_runs_select_own" ON scrape_runs
  FOR SELECT USING (user_id = auth.uid());
-- Inserts/updates happen through the service client (cron + webhook callback
-- run without a user session), so no user-facing insert/update policy.

-- Per-contact scrape failure tracking: 404/private/renamed profiles back off,
-- and after N consecutive failures the URL-repair resolver (phase 3) kicks in.
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS scrape_failed_at timestamptz;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS scrape_failure_count INT NOT NULL DEFAULT 0;

COMMENT ON COLUMN contacts.scrape_failure_count IS 'Consecutive failed scrape attempts; reset to 0 on a successful scrape (plan 29)';
