-- Plan 29: data subscriptions — admin-curated prospect/company bundles
-- Users subscribe from Settings; bundle prospects are copied into their
-- contacts via the merge engine and kept fresh by background sync. Bundle
-- content is written exclusively by the service-role client (publish flow);
-- user-token clients can only read published content they subscribe to.

-- ═══════════════════════════════════════════════════════════
-- 1. data_bundles — the catalog
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS data_bundles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  version int NOT NULL DEFAULT 0,
  staging_version int,
  staging_claimed_at timestamptz,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  prospect_count int NOT NULL DEFAULT 0,
  company_count int NOT NULL DEFAULT 0,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE data_bundles IS 'Admin-curated data bundles (prospect lists + company databases). Written only via the service-role publish flow; version 0 = never published.';
COMMENT ON COLUMN data_bundles.version IS 'Last COMMITTED publish version. Subscriber deltas are always bounded by this value pinned at sync start — staged rows are never applied.';
COMMENT ON COLUMN data_bundles.staging_version IS 'Publish lock: set to version+1 by beginPublish via conditional UPDATE; cleared by finalize/abort. A second publish is rejected while set and unexpired.';
COMMENT ON COLUMN data_bundles.staging_claimed_at IS 'When the publish lock was claimed; locks older than the expiry window may be reclaimed.';
COMMENT ON COLUMN data_bundles.prospect_count IS 'Denormalized live-prospect count, recomputed at finalize — read by browse cards without touching bundle_prospects.';

-- ═══════════════════════════════════════════════════════════
-- 2. bundle_prospects — versioned bundle content
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS bundle_prospects (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bundle_id int NOT NULL REFERENCES data_bundles(id) ON DELETE CASCADE,
  linkedin_url text NOT NULL,
  payload jsonb NOT NULL,
  payload_schema_version int NOT NULL DEFAULT 1,
  payload_hash text NOT NULL,
  version_added int NOT NULL,
  version_updated int NOT NULL,
  version_last_seen int NOT NULL,
  removed_in_version int,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (bundle_id, linkedin_url)
);

COMMENT ON TABLE bundle_prospects IS 'One row per prospect per bundle. payload is a CareerVine-owned BundleProspectPayloadV1 (never a scraper-native format); linkedin_url is canonical.';
COMMENT ON COLUMN bundle_prospects.payload_schema_version IS 'Payload contract version. Sync skips-and-reports unknown versions instead of crashing, so future contracts can roll out gradually.';
COMMENT ON COLUMN bundle_prospects.payload_hash IS 'sha256 of the canonical payload JSON — cheap change detection so re-publishing identical data causes zero version churn.';
COMMENT ON COLUMN bundle_prospects.version_updated IS 'Bumped when payload_hash changes. Subscriber apply delta: version_updated > synced_version AND version_updated <= pinned committed version.';
COMMENT ON COLUMN bundle_prospects.version_last_seen IS 'Bumped every publish the prospect appears in; finalize soft-removes rows not seen in the staging version.';
COMMENT ON COLUMN bundle_prospects.removed_in_version IS 'Soft delete for delta sync (NULL = live). Re-adding a prospect clears it.';

CREATE INDEX IF NOT EXISTS bundle_prospects_delta_idx
  ON bundle_prospects (bundle_id, version_updated);

CREATE INDEX IF NOT EXISTS bundle_prospects_removed_idx
  ON bundle_prospects (bundle_id, removed_in_version) WHERE removed_in_version IS NOT NULL;

-- ═══════════════════════════════════════════════════════════
-- 3. bundle_companies — display/provenance links
-- ═══════════════════════════════════════════════════════════
-- Company/location data itself is upserted into the global shared tables
-- (companies / locations / company_locations) at publish time via the
-- findOrCreateCompany identity chain; these rows only record membership so
-- browse cards can show counts and a company list.
CREATE TABLE IF NOT EXISTS bundle_companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bundle_id int NOT NULL REFERENCES data_bundles(id) ON DELETE CASCADE,
  company_id int NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (bundle_id, company_id)
);

-- ═══════════════════════════════════════════════════════════
-- 4. bundle_subscriptions — user ↔ bundle
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS bundle_subscriptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bundle_id int NOT NULL REFERENCES data_bundles(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed')),
  synced_version int NOT NULL DEFAULT 0,
  last_synced_at timestamptz,
  sync_claimed_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, bundle_id)
);

COMMENT ON COLUMN bundle_subscriptions.synced_version IS 'Last FULLY applied bundle version; advances only to the version pinned at sync start, only when both apply and removal phases complete. Reset to 0 on resubscribe (idempotent full re-apply).';
COMMENT ON COLUMN bundle_subscriptions.sync_claimed_until IS 'Serialization claim: sync drivers (fan-out worker, cron, opportunistic, user-driven apply) take this atomically before applying, so concurrent syncs cannot race the fingerprint bookkeeping.';
COMMENT ON COLUMN bundle_subscriptions.status IS 'unsubscribed rows are kept (UNIQUE holds, history survives, resubscribe is a status flip). Sync never runs for unsubscribed rows.';

CREATE INDEX IF NOT EXISTS bundle_subscriptions_stale_idx
  ON bundle_subscriptions (bundle_id, synced_version) WHERE status = 'active';

-- ═══════════════════════════════════════════════════════════
-- 5. bundle_subscription_contacts — membership linkage
-- ═══════════════════════════════════════════════════════════
-- Records which contacts a subscription supplied and whether the bundle
-- CREATED the contact (removable on unsubscribe) or merged into a
-- pre-existing one (never removable). Touched/fingerprint state deliberately
-- does NOT live here: one contact has one baseline regardless of how many
-- bundles supply it — that state is per (user, contact) in
-- bundle_contact_state, or overlapping bundles would poison each other.
CREATE TABLE IF NOT EXISTS bundle_subscription_contacts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id int NOT NULL REFERENCES bundle_subscriptions(id) ON DELETE CASCADE,
  contact_id int NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  bundle_prospect_id int REFERENCES bundle_prospects(id) ON DELETE SET NULL,
  linkedin_url text NOT NULL,
  created_by_bundle boolean NOT NULL,
  first_applied_version int NOT NULL,
  last_applied_version int NOT NULL,
  last_applied_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (subscription_id, contact_id)
);

COMMENT ON COLUMN bundle_subscription_contacts.bundle_prospect_id IS 'Durable removal-correlation key: contacts.linkedin_url can be rewritten (canonical upgrades) or user-edited, so removal matching must not depend on it.';
COMMENT ON COLUMN bundle_subscription_contacts.linkedin_url IS 'Canonical URL at apply time — debugging aid and secondary correlation key.';
COMMENT ON COLUMN bundle_subscription_contacts.created_by_bundle IS 'true = importPeopleChunk created the contact for this bundle (deletable on unsubscribe/removal if untouched and no sibling subscription links it); false = merged into a pre-existing contact (never deleted by bundle machinery).';

CREATE INDEX IF NOT EXISTS bundle_subscription_contacts_contact_idx
  ON bundle_subscription_contacts (contact_id);

-- ═══════════════════════════════════════════════════════════
-- 6. bundle_contact_state — per-user-per-contact touched state
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS bundle_contact_state (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  contact_id int NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  applied_fingerprint text,
  user_touched boolean NOT NULL DEFAULT false,
  apply_started_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, contact_id)
);

COMMENT ON TABLE bundle_contact_state IS 'Shared across ALL of a user''s subscriptions: fingerprint baseline + sticky user_touched flag that gates bundle-driven contact deletion. Deterministic by design — no timestamp heuristics anywhere near a delete decision.';
COMMENT ON COLUMN bundle_contact_state.applied_fingerprint IS 'Hash of the user-editable surface captured after the last bundle apply (computed from the pre-apply snapshot + merge results, never re-read). Drift at the next pre-apply check means the user edited the contact.';
COMMENT ON COLUMN bundle_contact_state.user_touched IS 'Sticky: once true, bundle machinery never deletes this contact. Set when fingerprint drift is detected outside an interrupted-apply recovery.';
COMMENT ON COLUMN bundle_contact_state.apply_started_at IS 'In-flight marker. If set when a sync begins, the prior apply crashed mid-write: refresh the baseline WITHOUT promoting drift to touched (a one-run false negative beats a permanent false positive).';

-- ═══════════════════════════════════════════════════════════
-- 7. RLS
-- ═══════════════════════════════════════════════════════════
ALTER TABLE data_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_subscription_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_contact_state ENABLE ROW LEVEL SECURITY;

-- Catalog: browse cards are visible to everyone signed in. No write policies
-- anywhere on bundle content — publishing runs on the service-role client,
-- and the ABSENCE of insert/update/delete policies is what locks users out.
CREATE POLICY "data_bundles_select_published" ON data_bundles
  FOR SELECT TO authenticated USING (status = 'published');

-- Content (prospect payloads include emails): readable only with an active
-- subscription — not a free harvest surface for any authenticated user.
CREATE POLICY "bundle_prospects_select_subscribed" ON bundle_prospects
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM bundle_subscriptions bs
      WHERE bs.bundle_id = bundle_prospects.bundle_id
        AND bs.user_id = auth.uid()
        AND bs.status = 'active'
    )
  );

CREATE POLICY "bundle_companies_select_subscribed" ON bundle_companies
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM bundle_subscriptions bs
      WHERE bs.bundle_id = bundle_companies.bundle_id
        AND bs.user_id = auth.uid()
        AND bs.status = 'active'
    )
  );

CREATE POLICY "bundle_subscriptions_select_own" ON bundle_subscriptions
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "bundle_subscriptions_insert_own" ON bundle_subscriptions
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "bundle_subscriptions_update_own" ON bundle_subscriptions
  FOR UPDATE USING (user_id = auth.uid());

CREATE POLICY "bundle_subscriptions_delete_own" ON bundle_subscriptions
  FOR DELETE USING (user_id = auth.uid());

-- Linkage: scoped via the parent subscription, and writes additionally prove
-- the contact belongs to the caller — contact_id is an enumerable integer, so
-- without the WITH CHECK a client could point linkage rows at other users'
-- contacts and skew delete decisions.
CREATE POLICY "bundle_subscription_contacts_select_own" ON bundle_subscription_contacts
  FOR SELECT USING (
    subscription_id IN (SELECT id FROM bundle_subscriptions WHERE user_id = auth.uid())
  );

CREATE POLICY "bundle_subscription_contacts_insert_own" ON bundle_subscription_contacts
  FOR INSERT WITH CHECK (
    subscription_id IN (SELECT id FROM bundle_subscriptions WHERE user_id = auth.uid())
    AND EXISTS (
      SELECT 1 FROM contacts c WHERE c.id = contact_id AND c.user_id = auth.uid()
    )
  );

CREATE POLICY "bundle_subscription_contacts_update_own" ON bundle_subscription_contacts
  FOR UPDATE USING (
    subscription_id IN (SELECT id FROM bundle_subscriptions WHERE user_id = auth.uid())
  ) WITH CHECK (
    subscription_id IN (SELECT id FROM bundle_subscriptions WHERE user_id = auth.uid())
    AND EXISTS (
      SELECT 1 FROM contacts c WHERE c.id = contact_id AND c.user_id = auth.uid()
    )
  );

CREATE POLICY "bundle_subscription_contacts_delete_own" ON bundle_subscription_contacts
  FOR DELETE USING (
    subscription_id IN (SELECT id FROM bundle_subscriptions WHERE user_id = auth.uid())
  );

CREATE POLICY "bundle_contact_state_select_own" ON bundle_contact_state
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "bundle_contact_state_insert_own" ON bundle_contact_state
  FOR INSERT WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM contacts c WHERE c.id = contact_id AND c.user_id = auth.uid()
    )
  );

CREATE POLICY "bundle_contact_state_update_own" ON bundle_contact_state
  FOR UPDATE USING (user_id = auth.uid());

CREATE POLICY "bundle_contact_state_delete_own" ON bundle_contact_state
  FOR DELETE USING (user_id = auth.uid());
