-- Plan 29 (CAR-15) phase 2: contact_scrape_snapshots.
--
-- One row per ingested scrape: a small normalized subset of what the profile
-- looked like at that moment. Two jobs:
--   1. Baseline for signals persisted nowhere else — hiring / openToWork flips
--      are only detectable against a prior snapshot (§5).
--   2. Audit trail: every change event is explainable by diffing two snapshots.
--
-- Dawson's decision §9.4: snapshot table yes. Volume is negligible (~2k
-- rows/month at full cadence).

CREATE TABLE IF NOT EXISTS contact_scrape_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  contact_id INT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  scrape_run_id BIGINT REFERENCES scrape_runs(id) ON DELETE SET NULL,
  scraped_at timestamptz NOT NULL DEFAULT now(),
  snapshot jsonb NOT NULL
);

COMMENT ON TABLE contact_scrape_snapshots IS 'Normalized per-scrape profile snapshot (plan 29): diff baseline for hiring/openToWork flips + audit trail for change events.';
COMMENT ON COLUMN contact_scrape_snapshots.snapshot IS 'Normalized subset: headline, location text, photo presence, hiring, open_to_work, certification names, employment rows (company ids/titles/months). NOT the raw actor payload.';

-- The diff reads "latest snapshot per contact" — index for that access path.
CREATE INDEX IF NOT EXISTS contact_scrape_snapshots_contact_scraped_idx
  ON contact_scrape_snapshots (contact_id, scraped_at DESC);

ALTER TABLE contact_scrape_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contact_scrape_snapshots_select_own" ON contact_scrape_snapshots;
CREATE POLICY "contact_scrape_snapshots_select_own" ON contact_scrape_snapshots
  FOR SELECT USING (user_id = auth.uid());
-- Writes happen through the service client (webhook ingest) — no user-facing
-- insert/update/delete policies.
