-- Plan 29 (CAR-15) phase 0: contact_change_events.
--
-- Persistent rails for surfacing "something changed about a contact worth an
-- outreach touch" — work anniversaries first (phase 0, derived from stored
-- start_month, no scraping), later profile-scrape diffs (job change, promotion,
-- hiring/openToWork flips — phases 2/3). One row per detected change, deduped
-- on a stable key so re-running the producer never double-surfaces.
--
-- Lifecycle: status 'new' → surfaces in the home Up Next feed → user actions it
-- ('actioned'), dismisses it ('dismissed'), or snoozes it ('snoozed'). Only
-- 'new' rows surface; the unique (user_id, dedupe_key) + ON CONFLICT DO NOTHING
-- producer means a dismissed/actioned event is never revived.
--
-- tier: 1 = act now (job change, promotion) → outreach suggestion; 2 = touchpoint
-- (anniversary, certification, location) → suggestion; 3 = silent data refresh
-- (photo/headline) → recorded for audit, never surfaced as a suggestion.

CREATE TABLE IF NOT EXISTS contact_change_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  contact_id INT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  type text NOT NULL,
  tier smallint NOT NULL DEFAULT 2 CHECK (tier IN (1, 2, 3)),
  dedupe_key text NOT NULL,
  headline text NOT NULL,
  evidence text,
  suggested_title text,
  suggested_description text,
  old_value jsonb,
  new_value jsonb,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'actioned', 'dismissed', 'snoozed')),
  snoozed_until timestamptz,
  detected_at timestamptz NOT NULL DEFAULT now(),
  actioned_at timestamptz,
  UNIQUE (user_id, dedupe_key)
);

COMMENT ON TABLE contact_change_events IS 'Detected contact changes worth an outreach touch (anniversaries now; scrape diffs later). One row per change, deduped on (user_id, dedupe_key); only status=new surfaces in the feed.';
COMMENT ON COLUMN contact_change_events.dedupe_key IS 'Stable idempotency key, e.g. anniversary:<contactId>:<companyId>:<year> or company_change:<contactId>:<hash>. Producer upserts ON CONFLICT DO NOTHING.';
COMMENT ON COLUMN contact_change_events.tier IS '1 = act now (job change, promotion); 2 = touchpoint (anniversary, cert, location); 3 = silent data refresh (never surfaced as a suggestion)';

CREATE INDEX IF NOT EXISTS contact_change_events_user_status_idx ON contact_change_events (user_id, status);
CREATE INDEX IF NOT EXISTS contact_change_events_contact_idx ON contact_change_events (contact_id);

ALTER TABLE contact_change_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "contact_change_events_select_own" ON contact_change_events
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "contact_change_events_insert_own" ON contact_change_events
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "contact_change_events_update_own" ON contact_change_events
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "contact_change_events_delete_own" ON contact_change_events
  FOR DELETE USING (user_id = auth.uid());
