-- Plan 24 Phase 1: company pages, office locations & LinkedIn-scrape import
-- Adds: company LinkedIn metadata + UPDATE policy, company office registry,
-- per-employment location/provenance columns, contact network tiers and
-- scrape provenance, the target-company recruiting layer, email provenance
-- and bounce tracking, and import-suppression tombstones.

-- ═══════════════════════════════════════════════════════════
-- 0. Recover a lost migration
-- ═══════════════════════════════════════════════════════════
-- contact_companies.location was added by
-- careervine/supabase/migrations/20250217_add_location_to_contact_companies.sql
-- (commit 9bec200) and deleted in 9c718fe without being re-created when
-- migrations moved to the repo root. The column exists in production (the
-- manual add-company UI writes it on every insert); this re-tracks it so
-- fresh environments match production. No-op on production.
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS location TEXT;

COMMENT ON COLUMN contact_companies.location IS 'Legacy free-text job location from manual entry (e.g., "San Francisco, CA"). Scraped imports use location_id/location_raw instead.';

-- ═══════════════════════════════════════════════════════════
-- 1. companies — LinkedIn metadata + missing UPDATE policy
-- ═══════════════════════════════════════════════════════════
ALTER TABLE companies ADD COLUMN IF NOT EXISTS linkedin_company_id text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS linkedin_url text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS universal_name text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url text;

COMMENT ON COLUMN companies.linkedin_company_id IS 'Stable LinkedIn numeric company id (from experience[].companyId) — primary join key for scraped data';
COMMENT ON COLUMN companies.universal_name IS 'LinkedIn company slug (e.g., "google")';

CREATE UNIQUE INDEX IF NOT EXISTS companies_linkedin_company_id_idx
  ON companies (linkedin_company_id) WHERE linkedin_company_id IS NOT NULL;

-- companies had SELECT + INSERT policies only. Without UPDATE, claiming an
-- existing name-only row by backfilling linkedin_company_id silently affects
-- 0 rows under RLS (the import path runs on a user-token client).
DROP POLICY IF EXISTS "companies_update_authenticated" ON companies;
CREATE POLICY "companies_update_authenticated" ON companies
  FOR UPDATE USING (auth.uid() IS NOT NULL);

-- ═══════════════════════════════════════════════════════════
-- 2. company_locations — auto-managed office registry
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS company_locations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  location_id int NOT NULL REFERENCES locations(id),
  source text NOT NULL DEFAULT 'scraped' CHECK (source IN ('scraped', 'manual')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, location_id)
);

COMMENT ON TABLE company_locations IS 'Known office locations per company. Rows established automatically by import rule 1 (experience-level locations) or seeded manually; anchor for location-scoped recruiting intel.';

ALTER TABLE company_locations ENABLE ROW LEVEL SECURITY;

-- Shared lookup data (mirrors locations): readable + insertable by any
-- authenticated user; deletable for phantom-office correction. No UPDATE
-- policy — the importer inserts with ON CONFLICT DO NOTHING.
CREATE POLICY "company_locations_select" ON company_locations
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "company_locations_insert" ON company_locations
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "company_locations_delete" ON company_locations
  FOR DELETE TO authenticated USING (true);

-- ═══════════════════════════════════════════════════════════
-- 3. contact_companies — per-employment location, provenance, staleness
-- ═══════════════════════════════════════════════════════════
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS location_id int REFERENCES locations(id);
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS location_source text CHECK (location_source IN ('experience', 'profile_match', 'manual'));
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS location_raw text;
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS workplace_type text CHECK (workplace_type IN ('on_site', 'hybrid', 'remote'));
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS employment_type text;
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'manual' CHECK (source IN ('scraped', 'manual'));
ALTER TABLE contact_companies ADD COLUMN IF NOT EXISTS scraped_at timestamptz;

COMMENT ON COLUMN contact_companies.location_id IS 'Normalized metro-grain employment location';
COMMENT ON COLUMN contact_companies.location_source IS 'How the location was determined: experience = stated on the LinkedIn role; profile_match = inferred from profile location matching a known office; manual = user-entered';
COMMENT ON COLUMN contact_companies.location_raw IS 'Original scraped location string, kept for re-normalization when the alias map improves';
COMMENT ON COLUMN contact_companies.source IS 'Row provenance for the merge engine: only scraped rows may be auto-updated/removed by re-imports';
COMMENT ON COLUMN contact_companies.scraped_at IS 'When this employment fact was last confirmed by a scrape';

-- ═══════════════════════════════════════════════════════════
-- 4. contacts — scrape provenance, staleness, network segregation
-- ═══════════════════════════════════════════════════════════
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS headline text;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS persona text CHECK (persona IN ('alum_product', 'alum_other', 'product_peer', 'product_leader', 'recruiter'));
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS review_note text;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS verified_school text CHECK (verified_school IN ('BYU', 'BYU-Idaho', 'Marriott', 'none'));
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS import_source text;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS import_meta jsonb;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS public_identifier text;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS last_scraped_at timestamptz;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS network_status text NOT NULL DEFAULT 'active' CHECK (network_status IN ('active', 'prospect', 'bench'));
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS stage_override text;

COMMENT ON COLUMN contacts.persona IS 'Pipeline-verified persona (matches the scrape pipeline''s verified_persona enum)';
COMMENT ON COLUMN contacts.review_note IS 'AI review reasoning from the scrape pipeline (pipeline.review_reason)';
COMMENT ON COLUMN contacts.verified_school IS 'Agent-verified school affiliation from the pipeline (identity.school) — cross-check for the contact_schools-derived alum badge';
COMMENT ON COLUMN contacts.import_source IS 'Scrape provenance, e.g. "apify:mini_a,c2:2026-07_tranche1"';
COMMENT ON COLUMN contacts.import_meta IS 'Remaining pipeline provenance block: adjacency_score, selection_reason, review_sheet, priority_rank, history[]';
COMMENT ON COLUMN contacts.public_identifier IS 'LinkedIn profile slug — secondary dedupe key after canonical linkedin_url';
COMMENT ON COLUMN contacts.last_scraped_at IS 'When this contact''s data was last refreshed by a scrape ("data as of")';
COMMENT ON COLUMN contacts.network_status IS 'Network tier: active = the real hand-curated network; prospect = SELECTED imports in play for outreach; bench = dormant imported data, excluded from all outreach/suggestion surfaces';
COMMENT ON COLUMN contacts.stage_override IS 'Manual override for the derived outreach stage (e.g. outreach happened via LinkedIn DM)';

-- Dedupe lookups during bulk import + the default-view network filter.
CREATE INDEX IF NOT EXISTS contacts_linkedin_url_idx ON contacts (linkedin_url);
CREATE INDEX IF NOT EXISTS contacts_public_identifier_idx ON contacts (public_identifier);
CREATE INDEX IF NOT EXISTS contacts_user_network_status_idx ON contacts (user_id, network_status);

-- ═══════════════════════════════════════════════════════════
-- 5. target_companies — the recruiting layer (user-scoped)
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS target_companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id int NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  priority_score numeric,
  tier text,
  program_name text,
  app_window_text text,
  next_app_date date,
  status text NOT NULL DEFAULT 'researching' CHECK (status IN ('researching', 'outreach_active', 'applied', 'interviewing', 'closed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, company_id)
);

COMMENT ON COLUMN target_companies.tier IS 'Segment/geo label from the target sheet (e.g. "Utah/Silicon Slopes", "Big Tech")';
COMMENT ON COLUMN target_companies.app_window_text IS 'Free-text application-window hint imported from the sheet — display only, never sorted or parsed';
COMMENT ON COLUMN target_companies.next_app_date IS 'Real application date set by hand when learned; the only field sorting/alerts use';

ALTER TABLE target_companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "target_companies_select_own" ON target_companies
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "target_companies_insert_own" ON target_companies
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "target_companies_update_own" ON target_companies
  FOR UPDATE USING (user_id = auth.uid());

CREATE POLICY "target_companies_delete_own" ON target_companies
  FOR DELETE USING (user_id = auth.uid());

-- ═══════════════════════════════════════════════════════════
-- 6. target_company_notes — timestamped recruiting-intel log
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS target_company_notes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_company_id int NOT NULL REFERENCES target_companies(id) ON DELETE CASCADE,
  note text NOT NULL,
  location_id int REFERENCES locations(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN target_company_notes.location_id IS 'Optional office tag so intel can be scoped to a company location';

ALTER TABLE target_company_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "target_company_notes_select" ON target_company_notes
  FOR SELECT USING (
    target_company_id IN (SELECT id FROM target_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "target_company_notes_insert" ON target_company_notes
  FOR INSERT WITH CHECK (
    target_company_id IN (SELECT id FROM target_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "target_company_notes_update" ON target_company_notes
  FOR UPDATE USING (
    target_company_id IN (SELECT id FROM target_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "target_company_notes_delete" ON target_company_notes
  FOR DELETE USING (
    target_company_id IN (SELECT id FROM target_companies WHERE user_id = auth.uid())
  );

-- ═══════════════════════════════════════════════════════════
-- 7. contact_emails — provenance + bounce tracking
-- ═══════════════════════════════════════════════════════════
ALTER TABLE contact_emails ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'scraped', 'pattern_guessed', 'verified'));
ALTER TABLE contact_emails ADD COLUMN IF NOT EXISTS bounced_at timestamptz;

COMMENT ON COLUMN contact_emails.source IS 'Where the address came from. Lifecycle is monotonic (verified > scraped > pattern_guessed) — re-imports may upgrade, never downgrade';
COMMENT ON COLUMN contact_emails.bounced_at IS 'Set when an NDR is detected for this address; bounced addresses surface distinctly, never as "no reply"';

-- ═══════════════════════════════════════════════════════════
-- 8. suppressed_imports — deletion tombstones
-- ═══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS suppressed_imports (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  linkedin_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, linkedin_url)
);

COMMENT ON TABLE suppressed_imports IS 'Tombstones written when an imported contact is deleted; bulk import skips these so deleted junk does not resurrect on the next tranche. linkedin_url is stored in canonical form.';

ALTER TABLE suppressed_imports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "suppressed_imports_select_own" ON suppressed_imports
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "suppressed_imports_insert_own" ON suppressed_imports
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "suppressed_imports_delete_own" ON suppressed_imports
  FOR DELETE USING (user_id = auth.uid());
