-- Supabase migration generated from database/v0.sql
-- Apply via `supabase db push` or `supabase db reset`

CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE,
  "phone" varchar,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "contacts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "name" varchar NOT NULL,
  "industry" varchar,
  "role" varchar,
  "linkedin_url" varchar,
  "notes" text,
  "met_through" text,
  "follow_up_frequency_days" int,
  "preferred_contact_method" varchar,
  "preferred_contact_value" varchar
);

CREATE TABLE IF NOT EXISTS "contact_emails" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contact_id" int NOT NULL,
  "email" varchar,
  "is_primary" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "contact_phones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contact_id" int NOT NULL,
  "phone" varchar NOT NULL,
  "is_primary" boolean NOT NULL DEFAULT false,
  "type" varchar NOT NULL DEFAULT 'mobile'
);

CREATE TABLE IF NOT EXISTS "companies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "contact_companies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contact_id" int NOT NULL,
  "company_id" int NOT NULL,
  "title" varchar,
  "start_date" date,
  "end_date" date,
  "is_current" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "schools" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "contact_schools" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contact_id" int NOT NULL,
  "school_id" int NOT NULL,
  "degree" varchar,
  "field_of_study" varchar,
  "start_year" int,
  "end_year" int
);

CREATE TABLE IF NOT EXISTS "user_companies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "company_id" int NOT NULL,
  "title" varchar,
  "start_date" date,
  "end_date" date,
  "is_current" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "user_schools" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "school_id" int NOT NULL,
  "degree" varchar,
  "field_of_study" varchar,
  "start_year" int,
  "end_year" int
);

CREATE TABLE IF NOT EXISTS "meetings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "meeting_date" timestamptz NOT NULL,
  "meeting_type" varchar NOT NULL,
  "notes" text,
  "transcript" text
);

CREATE TABLE IF NOT EXISTS "meeting_contacts" (
  "meeting_id" int NOT NULL,
  "contact_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "referrals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "referred_by_contact_id" int NOT NULL,
  "referred_contact_id" int NOT NULL,
  "referral_meeting_id" int,
  "notes" text
);

CREATE TABLE IF NOT EXISTS "interactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contact_id" int NOT NULL,
  "interaction_date" timestamptz NOT NULL,
  "interaction_type" varchar NOT NULL,
  "summary" text
);

CREATE TABLE IF NOT EXISTS "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "contact_tags" (
  "contact_id" int NOT NULL,
  "tag_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "bucket" varchar NOT NULL,
  "object_path" varchar NOT NULL,
  "file_name" varchar NOT NULL,
  "content_type" varchar,
  "file_size_bytes" bigint,
  "is_public" boolean NOT NULL DEFAULT false,
  "notes" text,
  "created_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "contact_attachments" (
  "contact_id" int NOT NULL,
  "attachment_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "meeting_attachments" (
  "meeting_id" int NOT NULL,
  "attachment_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "interaction_attachments" (
  "interaction_id" int NOT NULL,
  "attachment_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "post_meeting_action_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "meeting_id" int NOT NULL,
  "owner_type" varchar NOT NULL,
  "contact_id" int,
  "title" varchar NOT NULL,
  "description" text,
  "due_at" timestamptz,
  "is_completed" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz,
  "completed_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "follow_up_action_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "contact_id" int NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "due_at" timestamptz,
  "is_completed" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz,
  "completed_at" timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS contact_emails_contact_email_idx ON "contact_emails" ("contact_id", "email");
CREATE UNIQUE INDEX IF NOT EXISTS contact_phones_contact_phone_idx ON "contact_phones" ("contact_id", "phone");
CREATE UNIQUE INDEX IF NOT EXISTS contact_companies_unique_idx ON "contact_companies" ("contact_id", "company_id", "start_date");
CREATE UNIQUE INDEX IF NOT EXISTS contact_schools_unique_idx ON "contact_schools" ("contact_id", "school_id", "start_year");
CREATE UNIQUE INDEX IF NOT EXISTS user_companies_unique_idx ON "user_companies" ("user_id", "company_id", "start_date");
CREATE UNIQUE INDEX IF NOT EXISTS user_schools_unique_idx ON "user_schools" ("user_id", "school_id", "start_year");
CREATE UNIQUE INDEX IF NOT EXISTS meeting_contacts_unique_idx ON "meeting_contacts" ("meeting_id", "contact_id");
CREATE UNIQUE INDEX IF NOT EXISTS referrals_unique_idx ON "referrals" ("user_id", "referred_by_contact_id", "referred_contact_id", "referral_meeting_id");
CREATE UNIQUE INDEX IF NOT EXISTS tags_unique_idx ON "tags" ("user_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS contact_tags_unique_idx ON "contact_tags" ("contact_id", "tag_id");
CREATE UNIQUE INDEX IF NOT EXISTS attachments_path_idx ON "attachments" ("bucket", "object_path");
CREATE UNIQUE INDEX IF NOT EXISTS contact_attachments_unique_idx ON "contact_attachments" ("contact_id", "attachment_id");
CREATE UNIQUE INDEX IF NOT EXISTS meeting_attachments_unique_idx ON "meeting_attachments" ("meeting_id", "attachment_id");
CREATE UNIQUE INDEX IF NOT EXISTS interaction_attachments_unique_idx ON "interaction_attachments" ("interaction_id", "attachment_id");

ALTER TABLE "contacts" ADD CONSTRAINT contacts_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "contact_emails" ADD CONSTRAINT contact_emails_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "contact_phones" ADD CONSTRAINT contact_phones_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "contact_companies" ADD CONSTRAINT contact_companies_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "contact_companies" ADD CONSTRAINT contact_companies_company_fk FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "contact_schools" ADD CONSTRAINT contact_schools_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "contact_schools" ADD CONSTRAINT contact_schools_school_fk FOREIGN KEY ("school_id") REFERENCES "schools" ("id");
ALTER TABLE "user_companies" ADD CONSTRAINT user_companies_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_companies" ADD CONSTRAINT user_companies_company_fk FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "user_schools" ADD CONSTRAINT user_schools_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_schools" ADD CONSTRAINT user_schools_school_fk FOREIGN KEY ("school_id") REFERENCES "schools" ("id");
ALTER TABLE "meetings" ADD CONSTRAINT meetings_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "meeting_contacts" ADD CONSTRAINT meeting_contacts_meeting_fk FOREIGN KEY ("meeting_id") REFERENCES "meetings" ("id");
ALTER TABLE "meeting_contacts" ADD CONSTRAINT meeting_contacts_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "referrals" ADD CONSTRAINT referrals_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "referrals" ADD CONSTRAINT referrals_referrer_fk FOREIGN KEY ("referred_by_contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "referrals" ADD CONSTRAINT referrals_contact_fk FOREIGN KEY ("referred_contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "referrals" ADD CONSTRAINT referrals_meeting_fk FOREIGN KEY ("referral_meeting_id") REFERENCES "meetings" ("id");
ALTER TABLE "interactions" ADD CONSTRAINT interactions_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "tags" ADD CONSTRAINT tags_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "contact_tags" ADD CONSTRAINT contact_tags_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "contact_tags" ADD CONSTRAINT contact_tags_tag_fk FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");
ALTER TABLE "attachments" ADD CONSTRAINT attachments_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "contact_attachments" ADD CONSTRAINT contact_attachments_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "contact_attachments" ADD CONSTRAINT contact_attachments_attachment_fk FOREIGN KEY ("attachment_id") REFERENCES "attachments" ("id");
ALTER TABLE "meeting_attachments" ADD CONSTRAINT meeting_attachments_meeting_fk FOREIGN KEY ("meeting_id") REFERENCES "meetings" ("id");
ALTER TABLE "meeting_attachments" ADD CONSTRAINT meeting_attachments_attachment_fk FOREIGN KEY ("attachment_id") REFERENCES "attachments" ("id");
ALTER TABLE "interaction_attachments" ADD CONSTRAINT interaction_attachments_interaction_fk FOREIGN KEY ("interaction_id") REFERENCES "interactions" ("id");
ALTER TABLE "interaction_attachments" ADD CONSTRAINT interaction_attachments_attachment_fk FOREIGN KEY ("attachment_id") REFERENCES "attachments" ("id");
ALTER TABLE "post_meeting_action_items" ADD CONSTRAINT post_meeting_action_items_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "post_meeting_action_items" ADD CONSTRAINT post_meeting_action_items_meeting_fk FOREIGN KEY ("meeting_id") REFERENCES "meetings" ("id");
ALTER TABLE "post_meeting_action_items" ADD CONSTRAINT post_meeting_action_items_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
ALTER TABLE "follow_up_action_items" ADD CONSTRAINT follow_up_action_items_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "follow_up_action_items" ADD CONSTRAINT follow_up_action_items_contact_fk FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id");
